// web/src/contexts/catalog/views/AgentsView.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { AppSelect as Select } from "@/ui/AppSelect";
import { AppTextfield as Textfield } from "@/ui/AppTextfield";

import {
  disableAgent,
  enableAgent,
  listAgents,
  listProjects,
  runAgent,
  useCatalogStore,
} from "@/contexts/catalog/contract";
import { ActionMenu, type ActionMenuItem } from "@/ui/ActionMenu";
import { PageHeader } from "@/ui/PageHeader";
import { EnabledBadge } from "@/ui/status/EnabledBadge";
import { RunHistoryStrip } from "@/ui/RunHistoryStrip";
import { SortableTh } from "@/ui/SortableTh";
import { TablePager } from "@/ui/TablePager";
import { useBindStoreRefresh } from "@/platform/bind-store-refresh";
import { useServerTable } from "@/platform/useServerTable";
import { MAX_PAGE_LIMIT } from "@/kernel/pagination";
import { formatRunSuccessRate } from "@/kernel/run-success-rate";
import type { Order } from "@/platform/useClientPager";
import type { Agent, Project } from "@/contexts/catalog/types";

const AGENT_SORT_ALLOWED = [
  "name",
  "projectName",
  "enabled",
  "createdAt",
  "lastRunAt",
  "successRate",
] as const;

type EnabledFilter = "all" | "enabled" | "disabled";
const ENABLED_OPTIONS: Array<{ value: EnabledFilter; label: string }> = [
  { value: "enabled", label: "Enabled" },
  { value: "disabled", label: "Disabled" },
  { value: "all", label: "All" },
];

export function AgentsView() {
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();

  const initialSort = useMemo(() => {
    const v = searchParams.get("sort") ?? "";
    return (AGENT_SORT_ALLOWED as readonly string[]).includes(v) ? v : "name";
  }, [searchParams]);
  const initialOrder: Order = searchParams.get("order") === "desc" ? "desc" : "asc";
  const initialEnabled: EnabledFilter =
    (searchParams.get("enabled") as EnabledFilter) === "all" ||
    (searchParams.get("enabled") as EnabledFilter) === "disabled"
      ? (searchParams.get("enabled") as EnabledFilter)
      : "enabled";

  const [projects, setProjects] = useState<Project[]>([]);
  const [projectFilter, setProjectFilter] = useState(searchParams.get("projectId") || "all");
  const [enabledFilter, setEnabledFilter] = useState<EnabledFilter>(initialEnabled);
  const [query, setQuery] = useState(searchParams.get("q") ?? "");
  const [busyId, setBusyId] = useState<string | null>(null);
  const [pageError, setPageError] = useState("");

  const table = useServerTable<Agent>({
    defaultSort: initialSort,
    defaultOrder: initialOrder,
    watchSources: [projectFilter, enabledFilter, query],
    fetchPage: ({ limit, offset, sort, order }) =>
      listAgents({
        limit,
        offset,
        sort,
        order,
        projectId: projectFilter === "all" ? undefined : projectFilter || undefined,
        enabled: enabledFilter,
        q: query || undefined,
      }),
  });

  const loadProjects = useCallback(async () => {
    const result = await listProjects({ limit: MAX_PAGE_LIMIT, offset: 0 });
    setProjects(result.items);
  }, []);

  useEffect(() => {
    void loadProjects();
  }, [loadProjects]);

  useBindStoreRefresh(useCatalogStore.getState(), table.load);
  useBindStoreRefresh(useCatalogStore.getState(), loadProjects);

  useEffect(() => {
    const next = new URLSearchParams(searchParams);
    if (projectFilter && projectFilter !== "all") next.set("projectId", projectFilter);
    else next.delete("projectId");
    if (query) next.set("q", query);
    else next.delete("q");
    if (enabledFilter !== "enabled") next.set("enabled", enabledFilter);
    else next.delete("enabled");
    if (table.sort !== "name" || table.order !== "asc") {
      next.set("sort", table.sort);
      next.set("order", table.order);
    } else {
      next.delete("sort");
      next.delete("order");
    }
    if (next.toString() !== searchParams.toString()) {
      setSearchParams(next, { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectFilter, query, enabledFilter, table.sort, table.order]);

  function rowActions(agent: Agent): ActionMenuItem[] {
    const runsQ = new URLSearchParams({ agentId: agent.id });
    if (agent.projectId) runsQ.set("projectId", agent.projectId);
    const schedulesQ = new URLSearchParams({ agentId: agent.id, enabled: "all" });
    if (agent.projectId) schedulesQ.set("projectId", agent.projectId);
    return [
      { id: "open", label: "Open", to: `/agents/${agent.id}` },
      {
        id: "run",
        label: "Run now",
        disabled: busyId === agent.id || !agent.enabled,
      },
      { id: "view-runs", label: "View runs", to: `/runs?${runsQ.toString()}` },
      {
        id: "view-schedules",
        label: "View schedules",
        to: `/schedules?${schedulesQ.toString()}`,
      },
      {
        id: "toggle-enabled",
        label: agent.enabled ? "Disable" : "Enable",
        disabled: busyId === agent.id,
      },
    ];
  }

  async function runNow(agent: Agent) {
    setBusyId(agent.id);
    setPageError("");
    try {
      const run = await runAgent(agent.id);
      navigate(`/runs/${run.id}`);
    } catch (err) {
      setPageError(err instanceof Error ? err.message : "Failed to start run");
    } finally {
      setBusyId(null);
    }
  }

  async function toggleEnabled(agent: Agent) {
    setBusyId(agent.id);
    setPageError("");
    try {
      if (agent.enabled) await disableAgent(agent.id);
      else await enableAgent(agent.id);
      await table.load();
    } catch (err) {
      setPageError(err instanceof Error ? err.message : "Failed to update agent");
    } finally {
      setBusyId(null);
    }
  }

  function onAction(agent: Agent, actionId: string) {
    if (actionId === "run") void runNow(agent);
    else if (actionId === "toggle-enabled") void toggleEnabled(agent);
  }

  const projectOptions = [
    { value: "all", label: "All projects" },
    ...projects.map((p) => ({ value: p.id, label: p.name })),
  ];

  return (
    <div>
      <PageHeader
        title="Agents"
        subtitle="Manifest-synced and API-created agents across all projects"
      />

      {pageError || table.error ? (
        <div className="alert alert-error">{pageError || table.error}</div>
      ) : null}

      <div className="inline-form mb-7 task-filters">
        <div className="field">
          <label htmlFor="project-filter">Project</label>
          <Select
            inputId="project-filter"
            value={projectOptions.find((o) => o.value === projectFilter) ?? projectOptions[0]}
            options={projectOptions}
            onChange={(opt) => setProjectFilter(opt?.value ?? "all")}
            isSearchable={false}
          />
        </div>
        <div className="field">
          <label htmlFor="enabled-filter">Enabled</label>
          <Select
            inputId="enabled-filter"
            value={ENABLED_OPTIONS.find((o) => o.value === enabledFilter) ?? ENABLED_OPTIONS[0]}
            options={ENABLED_OPTIONS}
            onChange={(opt) => opt && setEnabledFilter(opt.value as EnabledFilter)}
            isSearchable={false}
          />
        </div>
        <div className="field flex-2">
          <label htmlFor="agent-search">Search</label>
          <Textfield
            id="agent-search"
            type="search"
            value={query}
            onChange={(e) => setQuery(e.currentTarget.value)}
            placeholder="Name, description, project…"
          />
        </div>
        <div className="field task-filter-count">
          <label>&nbsp;</label>
          <span className="muted">
            {table.total} agent{table.total === 1 ? "" : "s"}
          </span>
        </div>
      </div>

      {table.loading && table.items.length === 0 ? (
        <div className="empty">Loading agents…</div>
      ) : projects.length === 0 ? (
        <div className="empty">Add a project first, then Sync its gojo.yaml</div>
      ) : table.total === 0 ? (
        <div className="empty">
          {query || projectFilter !== "all" || enabledFilter !== "all"
            ? "No agents match these filters"
            : "No agents yet — Sync a project manifest to pull agents from gojo.yaml"}
        </div>
      ) : (
        <>
          <div className="table-wrap">
            <table className="data tasks-table">
              <thead>
                <tr>
                  <SortableTh
                    column="name"
                    label="Name"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <SortableTh
                    column="projectName"
                    label="Project"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <th className="tasks-col-runs">Recent runs</th>
                  <SortableTh
                    column="successRate"
                    label="Success"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <SortableTh
                    column="enabled"
                    label="Enabled"
                    sort={table.sort}
                    order={table.order}
                    defaultOrder="desc"
                    onSort={table.setSort}
                  />
                  <th>Profile</th>
                  <SortableTh
                    column="createdAt"
                    label="Created"
                    sort={table.sort}
                    order={table.order}
                    defaultOrder="desc"
                    onSort={table.setSort}
                  />
                  <th />
                </tr>
              </thead>
              <tbody>
                {table.items.map((agent) => (
                  <tr key={agent.id}>
                    <td>
                      <Link to={`/agents/${agent.id}`} className="entity-name">
                        {agent.name}
                      </Link>
                      {agent.description ? (
                        <div className="muted text-sm">{agent.description}</div>
                      ) : null}
                    </td>
                    <td>{agent.projectName || "—"}</td>
                    <td className="tasks-col-runs">
                      <RunHistoryStrip runs={agent.recentRuns ?? []} />
                    </td>
                    <td className="tasks-col-rate mono">
                      {formatRunSuccessRate(agent.recentRuns ?? [])}
                    </td>
                    <td>
                      <EnabledBadge enabled={agent.enabled} />
                    </td>
                    <td>{agent.profileName || "—"}</td>
                    <td className="mono muted">
                      {new Date(agent.createdAt).toLocaleString()}
                    </td>
                    <td className="actions-cell">
                      <ActionMenu
                        items={rowActions(agent)}
                        disabled={busyId === agent.id}
                        label={`Actions for ${agent.name}`}
                        onSelect={(id) => onAction(agent, id)}
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <TablePager
            page={table.page}
            pageCount={table.pages}
            rangeLabel={table.rangeLabel}
            total={table.total}
            onPageChange={table.setPage}
            loading={table.loading}
          />
        </>
      )}
    </div>
  );
}

// web/src/views/AgentsView.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";

import { disableAgent, enableAgent, listAgents, listProjects, runAgent } from "@/api";
import ActionMenu, { type ActionMenuItem } from "@/components/ActionMenu.vue";
import PageHeader from "@/components/PageHeader.vue";
import EnabledBadge from "@/components/status/EnabledBadge.vue";
import RunHistoryStrip from "@/components/RunHistoryStrip.vue";
import SortableTh from "@/components/SortableTh.vue";
import TablePager from "@/components/TablePager.vue";
import { useLiveRefresh } from "@/composables/useLiveQuery";
import { useServerTable } from "@/composables/useServerTable";
import { MAX_PAGE_LIMIT, type SortOrder } from "@/lib/pagination";
import { formatRunSuccessRate } from "@/lib/run-success-rate";
import type { Agent, Project } from "@/types";

const AGENT_SORT_ALLOWED = [
  "name",
  "projectName",
  "enabled",
  "createdAt",
  "lastRunAt",
  "successRate",
] as const;

const route = useRoute();
const router = useRouter();

function queryParam(key: string): string {
  const value = route.query[key];
  return typeof value === "string" ? value : "";
}

function initialSort(): string {
  const value = queryParam("sort");
  return (AGENT_SORT_ALLOWED as readonly string[]).includes(value) ? value : "name";
}

function initialOrder(): SortOrder {
  const value = queryParam("order");
  return value === "asc" || value === "desc" ? value : "asc";
}

function initialEnabled(): "all" | "enabled" | "disabled" {
  const value = queryParam("enabled");
  return value === "all" || value === "disabled" ? value : "enabled";
}

const projects = ref<Project[]>([]);
const projectFilter = ref(queryParam("projectId"));
const enabledFilter = ref<"all" | "enabled" | "disabled">(initialEnabled());
const query = ref(queryParam("q"));
const busyId = ref<string | null>(null);

const {
  page,
  pages,
  items: agents,
  total,
  loading,
  error,
  sort,
  order,
  setSort,
  rangeLabel,
  load,
} = useServerTable({
  defaultSort: initialSort(),
  defaultOrder: initialOrder(),
  watchSources: [projectFilter, enabledFilter, query],
  fetchPage: ({ limit, offset, sort: sortBy, order: sortOrder }) =>
    listAgents({
      limit,
      offset,
      sort: sortBy,
      order: sortOrder,
      projectId: projectFilter.value || undefined,
      enabled: enabledFilter.value,
      q: query.value || undefined,
    }),
});

async function loadProjects() {
  const result = await listProjects({ limit: MAX_PAGE_LIMIT, offset: 0 });
  projects.value = result.items;
}

function rowActions(agent: Agent): ActionMenuItem[] {
  return [
    {
      id: "open",
      label: "Open",
      to: { name: "agent-detail", params: { id: agent.id } },
    },
    {
      id: "run",
      label: "Run now",
      disabled: busyId.value === agent.id || !agent.enabled,
    },
    {
      id: "view-runs",
      label: "View runs",
      to: {
        name: "runs",
        query: {
          agentId: agent.id,
          ...(agent.projectId ? { projectId: agent.projectId } : {}),
        },
      },
    },
    {
      id: "view-schedules",
      label: "View schedules",
      to: {
        name: "schedules",
        query: {
          agentId: agent.id,
          ...(agent.projectId ? { projectId: agent.projectId } : {}),
          enabled: "all",
        },
      },
    },
    {
      id: "toggle-enabled",
      label: agent.enabled ? "Disable" : "Enable",
      disabled: busyId.value === agent.id,
    },
  ];
}

async function runNow(agent: Agent) {
  busyId.value = agent.id;
  error.value = "";
  try {
    const run = await runAgent(agent.id);
    await router.push(`/runs/${run.id}`);
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to start run";
  } finally {
    busyId.value = null;
  }
}

async function toggleEnabled(agent: Agent) {
  busyId.value = agent.id;
  error.value = "";
  try {
    if (agent.enabled) {
      await disableAgent(agent.id);
    } else {
      await enableAgent(agent.id);
    }
    await load();
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to update agent";
  } finally {
    busyId.value = null;
  }
}

function onAction(agent: Agent, actionId: string) {
  if (actionId === "run") {
    void runNow(agent);
  } else if (actionId === "toggle-enabled") {
    void toggleEnabled(agent);
  }
}

watch(
  () => [route.query.projectId, route.query.q, route.query.enabled] as const,
  ([projectId, q, enabled]) => {
    const nextProject = typeof projectId === "string" ? projectId : "";
    const nextQ = typeof q === "string" ? q : "";
    const nextEnabled =
      enabled === "all" || enabled === "disabled" || enabled === "enabled"
        ? enabled
        : "enabled";
    if (projectFilter.value !== nextProject) {
      projectFilter.value = nextProject;
    }
    if (query.value !== nextQ) {
      query.value = nextQ;
    }
    if (enabledFilter.value !== nextEnabled) {
      enabledFilter.value = nextEnabled;
    }
  },
);

watch([projectFilter, enabledFilter, query, sort, order], () => {
  const nextQuery = { ...route.query } as Record<string, string>;
  if (projectFilter.value) {
    nextQuery.projectId = projectFilter.value;
  } else {
    delete nextQuery.projectId;
  }
  if (query.value) {
    nextQuery.q = query.value;
  } else {
    delete nextQuery.q;
  }
  if (enabledFilter.value !== "enabled") {
    nextQuery.enabled = enabledFilter.value;
  } else {
    delete nextQuery.enabled;
  }
  if (sort.value !== "name" || order.value !== "asc") {
    nextQuery.sort = sort.value;
    nextQuery.order = order.value;
  } else {
    delete nextQuery.sort;
    delete nextQuery.order;
  }
  const same =
    (nextQuery.projectId ?? "") === queryParam("projectId") &&
    (nextQuery.q ?? "") === queryParam("q") &&
    (nextQuery.enabled ?? "") === queryParam("enabled") &&
    (nextQuery.sort ?? "") === queryParam("sort") &&
    (nextQuery.order ?? "") === queryParam("order");
  if (!same) {
    void router.replace({ query: nextQuery });
  }
});

useLiveRefresh({
  topics: ["agents", "runs", "overview"],
  refresh: load,
});
useLiveRefresh({
  topics: ["projects"],
  refresh: loadProjects,
});
</script>

<template>
  <div>
    <PageHeader
      title="Agents"
      subtitle="Manifest-synced and API-created agents across all projects"
    />

    <div v-if="error" class="alert alert-error">{{ error }}</div>

    <div class="inline-form mb-7 task-filters">
      <div class="field">
        <label for="project-filter">Project</label>
        <select id="project-filter" v-model="projectFilter">
          <option value="">All projects</option>
          <option v-for="project in projects" :key="project.id" :value="project.id">
            {{ project.name }}
          </option>
        </select>
      </div>
      <div class="field">
        <label for="enabled-filter">Enabled</label>
        <select id="enabled-filter" v-model="enabledFilter">
          <option value="enabled">Enabled</option>
          <option value="disabled">Disabled</option>
          <option value="all">All</option>
        </select>
      </div>
      <div class="field flex-2">
        <label for="agent-search">Search</label>
        <input
          id="agent-search"
          v-model="query"
          class="input"
          type="search"
          placeholder="Name, description, project…"
        />
      </div>
      <div class="field task-filter-count">
        <label>&nbsp;</label>
        <span class="muted">{{ total }} agent{{ total === 1 ? "" : "s" }}</span>
      </div>
    </div>

    <div v-if="loading && agents.length === 0" class="empty">Loading agents…</div>
    <div v-else-if="projects.length === 0" class="empty">
      Add a project first, then Sync its gojo.yaml
    </div>
    <div v-else-if="total === 0" class="empty">
      {{
        query || projectFilter || enabledFilter !== "all"
          ? "No agents match these filters"
          : "No agents yet — Sync a project manifest to pull agents from gojo.yaml"
      }}
    </div>
    <template v-else>
      <div class="table-wrap">
        <table class="data tasks-table">
          <thead>
            <tr>
              <SortableTh column="name" label="Name" :sort="sort" :order="order" @sort="setSort" />
              <SortableTh
                column="projectName"
                label="Project"
                :sort="sort"
                :order="order"
                @sort="setSort"
              />
              <th class="tasks-col-runs">Recent runs</th>
              <SortableTh
                column="successRate"
                label="Success"
                :sort="sort"
                :order="order"
                default-order="asc"
                @sort="setSort"
              />
              <SortableTh
                column="enabled"
                label="Enabled"
                :sort="sort"
                :order="order"
                default-order="desc"
                @sort="setSort"
              />
              <th>Profile</th>
              <SortableTh
                column="createdAt"
                label="Created"
                :sort="sort"
                :order="order"
                default-order="desc"
                @sort="setSort"
              />
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="agent in agents" :key="agent.id">
              <td>
                <RouterLink
                  :to="{ name: 'agent-detail', params: { id: agent.id } }"
                  class="entity-name"
                >
                  {{ agent.name }}
                </RouterLink>
                <div v-if="agent.description" class="muted text-sm">
                  {{ agent.description }}
                </div>
              </td>
              <td>{{ agent.projectName || "—" }}</td>
              <td class="tasks-col-runs">
                <RunHistoryStrip :runs="agent.recentRuns ?? []" />
              </td>
              <td class="tasks-col-rate mono">
                {{ formatRunSuccessRate(agent.recentRuns ?? []) }}
              </td>
              <td>
                <EnabledBadge :enabled="agent.enabled" />
              </td>
              <td>{{ agent.profileName || "—" }}</td>
              <td class="mono muted">{{ new Date(agent.createdAt).toLocaleString() }}</td>
              <td class="actions-cell">
                <ActionMenu
                  :items="rowActions(agent)"
                  :disabled="busyId === agent.id"
                  :label="`Actions for ${agent.name}`"
                  @select="(id) => onAction(agent, id)"
                />
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <TablePager
        v-model:page="page"
        :page-count="pages"
        :range-label="rangeLabel"
        :total="total"
      />
    </template>
  </div>
</template>

<style scoped>
.tasks-table :deep(th.tasks-col-runs),
.tasks-table :deep(td.tasks-col-runs) {
  width: 12rem;
  min-width: 12rem;
  text-align: right;
  vertical-align: middle;
}

.tasks-table :deep(th.tasks-col-rate),
.tasks-table :deep(td.tasks-col-rate) {
  width: 5.5rem;
  text-align: right;
  font-variant-numeric: tabular-nums;
}
</style>
