// web/src/contexts/access/views/LoginView.tsx
import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { AppTextfield as Textfield } from "@/ui/AppTextfield";
import { KeyRound as KeyIcon } from "lucide-react";

import { checkSession, login, probeSetupNeeded, setup } from "@/contexts/access/contract";
import { getHealth } from "@/contexts/operations/contract";
import { AppButton } from "@/ui/AppButton";
import { AppSectionMessage } from "@/ui/AppSectionMessage";
import { AppSpinner } from "@/ui/AppSpinner";
import { ApiError } from "@/infrastructure/api-error";

export function LoginView() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const [mode, setMode] = useState<"loading" | "setup" | "login">("loading");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [version, setVersion] = useState("");

  useEffect(() => {
    void (async () => {
      try {
        const health = await getHealth();
        setVersion(health.version);
        const session = await checkSession({ force: true });
        if (session) {
          const redirect = params.get("redirect") || "/";
          void navigate(redirect, { replace: true });
          return;
        }
        const needsSetup = await probeSetupNeeded();
        setMode(needsSetup ? "setup" : "login");
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unable to reach API");
        setMode("login");
      }
    })();
  }, [navigate, params]);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setError("");
    setBusy(true);
    try {
      if (mode === "setup") {
        await setup(username.trim(), password);
      } else {
        await login(username.trim(), password);
      }
      const redirect = params.get("redirect") || "/";
      void navigate(redirect, { replace: true });
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Request failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="auth-page">
      <div className="auth-box">
        <h1>gojo</h1>
        {mode === "setup" ? (
          <p className="auth-purpose">
            Create the admin account to finish setting up this instance.
          </p>
        ) : mode === "login" ? (
          <p className="auth-purpose">
            Scheduled agent orchestration — sign in to the ops console.
          </p>
        ) : (
          <p className="auth-purpose">Connecting…</p>
        )}

        {version ? <div className="mono muted text-sm mb-6">v{version}</div> : null}

        {error ? <AppSectionMessage appearance="error">{error}</AppSectionMessage> : null}

        {mode === "loading" ? (
          <AppSpinner size="large" />
        ) : (
          <form onSubmit={(e) => void submit(e)}>
            <div className="field">
              <label htmlFor="username">Username</label>
              <Textfield
                id="username"
                name="username"
                autoComplete="username"
                isRequired
                value={username}
                onChange={(e) => setUsername(e.currentTarget.value)}
              />
            </div>
            <div className="field">
              <label htmlFor="password">Password</label>
              <Textfield
                id="password"
                name="password"
                type="password"
                autoComplete="new-password"
                isRequired
                value={password}
                onChange={(e) => setPassword(e.currentTarget.value)}
              />
            </div>
            <AppButton
              variant="primary"
              className="w-full"
              type="submit"
              loading={busy}
              loadingLabel={mode === "setup" ? "Completing setup…" : "Signing in…"}
              iconBefore={<KeyIcon size={14} />}
            >
              {mode === "setup" ? "Complete setup" : "Sign in"}
            </AppButton>
          </form>
        )}
      </div>
    </div>
  );
}

// web/src/views/LoginView.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";

import { checkSession, getHealth, login, probeSetupNeeded, setup } from "@/api";
import AppButton from "@/components/AppButton.vue";
import { KeyRound } from "lucide-vue-next";
import { ApiError } from "@/types";

const router = useRouter();
const route = useRoute();

const mode = ref<"loading" | "setup" | "login">("loading");
const username = ref("");
const password = ref("");
const error = ref("");
const busy = ref(false);
const version = ref("");

onMounted(async () => {
  try {
    const health = await getHealth();
    version.value = health.version;

    // Force a probe on the login page so a stale "logged out" cache cannot
    // strand an already-authenticated browser after a soft reload.
    const session = await checkSession({ force: true });
    if (session) {
      const redirect = typeof route.query.redirect === "string" ? route.query.redirect : "/";
      await router.replace(redirect);
      return;
    }

    const needsSetup = await probeSetupNeeded();
    mode.value = needsSetup ? "setup" : "login";
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Unable to reach API";
    mode.value = "login";
  }
});

async function submit() {
  error.value = "";
  busy.value = true;
  try {
    if (mode.value === "setup") {
      await setup(username.value.trim(), password.value);
    } else {
      await login(username.value.trim(), password.value);
    }
    const redirect = typeof route.query.redirect === "string" ? route.query.redirect : "/";
    await router.replace(redirect);
  } catch (err) {
    error.value = err instanceof ApiError ? err.message : "Request failed";
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <div class="auth-page">
    <div class="auth-box">
      <h1>gojo</h1>
      <p v-if="mode === 'setup'" class="auth-purpose">
        Create the admin account to finish setting up this instance.
      </p>
      <p v-else-if="mode === 'login'" class="auth-purpose">
        Scheduled agent orchestration — sign in to the ops console.
      </p>
      <p v-else class="auth-purpose">Connecting…</p>

      <div v-if="version" class="mono muted text-sm mb-6">v{{ version }}</div>

      <div v-if="error" class="alert alert-error">{{ error }}</div>

      <form v-if="mode !== 'loading'" @submit.prevent="submit">
        <div class="field">
          <label for="username">Username</label>
          <input id="username" v-model="username" autocomplete="username" required />
        </div>
        <div class="field">
          <label for="password">Password</label>
          <input
            id="password"
            v-model="password"
            type="password"
            autocomplete="new-password"
            required
          />
        </div>
        <AppButton
          variant="primary"
          class="w-full"
          :icon="KeyRound"
          type="submit"
          :loading="busy"
          :loading-label="mode === 'setup' ? 'Completing setup…' : 'Signing in…'"
        >
          {{ mode === "setup" ? "Complete setup" : "Sign in" }}
        </AppButton>
      </form>
    </div>
  </div>
</template>
