// web/src/contexts/catalog/views/ProjectsView.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { AppTextfield as Textfield } from "@/ui/AppTextfield";
import { FolderOpen, Plus } from "lucide-react";

import { ActionMenu, type ActionMenuItem } from "@/ui/ActionMenu";
import { AppButton } from "@/ui/AppButton";
import { PageHeader } from "@/ui/PageHeader";
import { ConfirmDialog } from "@/ui/ConfirmDialog";
import { DirectoryPicker } from "@/contexts/operations/components/DirectoryPicker";
import { ModalDialog } from "@/ui/ModalDialog";
import { SortableTh } from "@/ui/SortableTh";
import { TablePager } from "@/ui/TablePager";
import { EnabledBadge } from "@/ui/status/EnabledBadge";
import { HealthBadge } from "@/ui/status/HealthBadge";
import { useBindStoreRefresh } from "@/platform/bind-store-refresh";
import { useServerTable } from "@/platform/useServerTable";
import {
  createProject,
  deleteProject,
  disableProject,
  enableProject,
  listProjects,
  syncProject,
  useCatalogStore,
} from "@/contexts/catalog/contract";
import { getProjectDoctor } from "@/contexts/operations/contract";
import {
  computeProjectHealth,
  type ProjectHealthSummary,
} from "@/kernel/project-manifest";
import type { Order } from "@/platform/useClientPager";
import type { Project } from "@/contexts/catalog/types";

const PROJECT_SORT_ALLOWED = ["name", "createdAt", "updatedAt", "defaultBranch"] as const;

function basename(path: string): string {
  const trimmed = path.replace(/[/\\]+$/, "");
  const parts = trimmed.split(/[/\\]/);
  return parts[parts.length - 1] || "project";
}

function configSummary(project: Project): string {
  if (!project.hasManifest && project.agentCount === 0) return "Not synced";
  return `${project.enabledAgentCount}/${project.agentCount} agents · ${project.enabledScheduleCount}/${project.scheduleCount} schedules`;
}

export function ProjectsView() {
  const [searchParams, setSearchParams] = useSearchParams();

  const initialSort = useMemo(() => {
    const v = searchParams.get("sort") ?? "";
    return (PROJECT_SORT_ALLOWED as readonly string[]).includes(v) ? v : "createdAt";
  }, [searchParams]);
  const initialOrder: Order = useMemo(() => {
    const v = searchParams.get("order");
    return v === "desc" ? "desc" : "asc";
  }, [searchParams]);

  const [query, setQuery] = useState("");
  const [hasOpenPrs, setHasOpenPrs] = useState(
    searchParams.get("hasOpenPrs") === "1" || searchParams.get("hasOpenPrs") === "true",
  );
  const [busyId, setBusyId] = useState<string | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  const [creating, setCreating] = useState(false);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [name, setName] = useState("");
  const [repoPath, setRepoPath] = useState("");
  const [formError, setFormError] = useState("");
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [removeTarget, setRemoveTarget] = useState<Project | null>(null);
  const [healthById, setHealthById] = useState<Record<string, ProjectHealthSummary>>({});
  const [healthLoading, setHealthLoading] = useState(false);

  const table = useServerTable<Project>({
    defaultSort: initialSort,
    defaultOrder: initialOrder,
    watchSources: [query, hasOpenPrs],
    fetchPage: ({ limit, offset, sort, order }) =>
      listProjects({
        limit,
        offset,
        sort,
        order,
        q: query || undefined,
        ...(hasOpenPrs ? { hasOpenPrs: true } : {}),
      }),
  });

  useEffect(() => {
    const next = new URLSearchParams(searchParams);
    if (table.sort !== "createdAt" || table.order !== "asc") {
      next.set("sort", table.sort);
      next.set("order", table.order);
    } else {
      next.delete("sort");
      next.delete("order");
    }
    if (hasOpenPrs) next.set("hasOpenPrs", "1");
    else next.delete("hasOpenPrs");
    if (next.toString() !== searchParams.toString()) {
      setSearchParams(next, { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [table.sort, table.order, hasOpenPrs]);

  const refreshHealth = useCallback(async (list: Project[]) => {
    if (list.length === 0) {
      setHealthById({});
      return;
    }
    setHealthLoading(true);
    const next: Record<string, ProjectHealthSummary> = {};
    await Promise.all(
      list.map(async (project) => {
        try {
          const doctor = await getProjectDoctor(project.id);
          next[project.id] = computeProjectHealth(project, doctor);
        } catch {
          next[project.id] = { score: null, level: "warn", label: "Unavailable" };
        }
      }),
    );
    setHealthById((prev) => ({ ...prev, ...next }));
    setHealthLoading(false);
  }, []);

  useEffect(() => {
    void refreshHealth(table.items);
  }, [table.items, refreshHealth]);

  const load = table.load;
  const catalogRefresh = useCallback(async () => {
    await load();
  }, [load]);
  useBindStoreRefresh(useCatalogStore.getState(), catalogRefresh);

  function healthFor(project: Project): ProjectHealthSummary {
    return (
      healthById[project.id] ?? {
        score: null,
        level: project.hasManifest ? "warn" : "missing",
        label: project.hasManifest ? "…" : "No manifest",
      }
    );
  }

  const navigate = useNavigate();

  function rowActions(project: Project): ActionMenuItem[] {
    return [
      { id: "open", label: "Open", to: `/projects/${project.id}` },
      { id: "sync", label: "Sync", disabled: busyId === project.id },
      {
        id: "toggle-enabled",
        label: project.enabled === false ? "Enable" : "Disable",
        disabled: busyId === project.id,
      },
      { id: "remove", label: "Remove", danger: true, disabled: busyId === project.id },
    ];
  }

  async function sync(project: Project) {
    setBusyId(project.id);
    setError("");
    setNotice("");
    try {
      const result = await syncProject(project.id);
      const leaf = result.sync.manifestPath
        ? result.sync.manifestPath.split(/[/\\]/).slice(-1)[0]
        : "no manifest";
      setNotice(
        `${project.name}: synced from ${leaf} — ${result.sync.profiles} profiles, ${result.sync.agents} agents, ${result.sync.schedules} schedules`,
      );
      await load();
      try {
        const doctor = await getProjectDoctor(project.id);
        setHealthById((prev) => ({
          ...prev,
          [project.id]: computeProjectHealth(result.project, doctor),
        }));
      } catch {
        // health refresh best-effort
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Sync failed");
    } finally {
      setBusyId(null);
    }
  }

  async function toggleEnabled(project: Project) {
    setBusyId(project.id);
    setError("");
    setNotice("");
    try {
      if (project.enabled === false) {
        await enableProject(project.id);
        setNotice(
          `${project.name}: enabled (runtime). Next Sync reapplies gojo.yaml if it disagrees.`,
        );
      } else {
        await disableProject(project.id);
        setNotice(
          `${project.name}: disabled (runtime). New runs stay off until enable or Sync.`,
        );
      }
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to update project");
    } finally {
      setBusyId(null);
    }
  }

  function onAction(project: Project, actionId: string) {
    if (actionId === "open") navigate(`/projects/${project.id}`);
    else if (actionId === "sync") void sync(project);
    else if (actionId === "toggle-enabled") void toggleEnabled(project);
    else if (actionId === "remove") setRemoveTarget(project);
  }

  async function confirmRemove() {
    const project = removeTarget;
    if (!project) return;
    setBusyId(project.id);
    setError("");
    setNotice("");
    try {
      await deleteProject(project.id);
      setRemoveTarget(null);
      setHealthById((prev) => {
        const { [project.id]: _removed, ...rest } = prev;
        return rest;
      });
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Remove failed");
    } finally {
      setBusyId(null);
    }
  }

  function onPicked(path: string) {
    setRepoPath(path);
    if (!name.trim()) setName(basename(path));
    setPickerOpen(false);
  }

  function openAdd() {
    setFormError("");
    setAddOpen(true);
  }

  function closeAdd() {
    if (creating || pickerOpen) return;
    setAddOpen(false);
    setFormError("");
  }

  async function addProject(e?: React.FormEvent) {
    e?.preventDefault();
    if (!name.trim() || !repoPath.trim()) {
      setFormError("Name and repository path are required");
      return;
    }
    setCreating(true);
    setFormError("");
    setNotice("");
    try {
      await createProject({ name: name.trim(), repoPath: repoPath.trim() });
      setName("");
      setRepoPath("");
      setAddOpen(false);
      await load();
    } catch (err) {
      setFormError(err instanceof Error ? err.message : "Failed to create project");
    } finally {
      setCreating(false);
    }
  }

  const totalDisplay = table.total;

  return (
    <div>
      <PageHeader
        title="Projects"
        subtitle="Registered repositories — sync manifests, check health, open details"
        actions={
          <AppButton
            variant="primary"
            onClick={openAdd}
            iconBefore={<Plus size={16} />}
          >
            Add project
          </AppButton>
        }
      />

      {error || table.error ? (
        <div className="alert alert-error">{error || table.error}</div>
      ) : null}
      {notice ? <div className="alert alert-success">{notice}</div> : null}

      <div className="inline-form mb-7 task-filters">
        <div className="field flex-2">
          <label htmlFor="project-search">Search</label>
          <Textfield
            id="project-search"
            type="search"
            value={query}
            onChange={(e) => setQuery(e.currentTarget.value)}
            placeholder="Name, path, id…"
          />
        </div>
        <div className="field">
          <label htmlFor="project-open-prs">Open PRs</label>
          <label className="checkbox-row" htmlFor="project-open-prs">
            <input
              id="project-open-prs"
              type="checkbox"
              checked={hasOpenPrs}
              onChange={(e) => setHasOpenPrs(e.currentTarget.checked)}
            />
            Has open PRs
          </label>
        </div>
        <div className="field task-filter-count">
          <label>&nbsp;</label>
          <span className="muted">
            {totalDisplay} project{totalDisplay === 1 ? "" : "s"}
          </span>
        </div>
      </div>

      {table.loading && table.items.length === 0 ? (
        <div className="empty">Loading projects…</div>
      ) : totalDisplay === 0 ? (
        <div className="empty">
          {query || hasOpenPrs
            ? "No projects match these filters"
            : "No projects yet — use Add project to register a repository"}
        </div>
      ) : (
        <>
          <div className="table-wrap">
            <table className="data">
              <thead>
                <tr>
                  <SortableTh
                    column="name"
                    label="Name"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <th>Status</th>
                  <th>Repo path</th>
                  <SortableTh
                    column="defaultBranch"
                    label="Branch"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <th>Config</th>
                  <th>Open PRs</th>
                  <th>
                    Health
                    {healthLoading ? <span className="muted text-sm"> …</span> : null}
                  </th>
                  <SortableTh
                    column="updatedAt"
                    label="Updated"
                    sort={table.sort}
                    order={table.order}
                    defaultOrder="desc"
                    onSort={table.setSort}
                  />
                  <th />
                </tr>
              </thead>
              <tbody>
                {table.items.map((project) => (
                  <tr key={project.id}>
                    <td>
                      <Link to={`/projects/${project.id}`} className="entity-name">
                        {project.name}
                      </Link>
                      <div className="mono muted text-sm">{project.id.slice(0, 10)}…</div>
                    </td>
                    <td>
                      <EnabledBadge enabled={project.enabled !== false} />
                    </td>
                    <td className="mono muted">{project.repoPath}</td>
                    <td className="mono">{project.defaultBranch}</td>
                    <td className="muted">{configSummary(project)}</td>
                    <td>
                      {project.openPrCount > 0 ? (
                        <Link
                          to={`/projects/${project.id}/overview#delivery`}
                          className="entity-name"
                        >
                          {project.openPrCount}
                        </Link>
                      ) : (
                        <span className="muted">—</span>
                      )}
                    </td>
                    <td>
                      <Link
                        to={`/projects/${project.id}/health`}
                        className="health-badge-link"
                      >
                        <HealthBadge
                          level={healthFor(project).level}
                          label={healthFor(project).label}
                        />
                      </Link>
                    </td>
                    <td className="mono muted">
                      {new Date(project.updatedAt).toLocaleString()}
                    </td>
                    <td className="actions-cell">
                      <ActionMenu
                        items={rowActions(project)}
                        disabled={busyId === project.id}
                        label={`Actions for ${project.name}`}
                        onSelect={(id) => onAction(project, id)}
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <TablePager
            page={table.page}
            pageCount={table.pages}
            rangeLabel={table.rangeLabel}
            total={table.total}
            onPageChange={table.setPage}
            loading={table.loading}
          />
        </>
      )}

      <ModalDialog
        open={addOpen}
        title="Add project"
        wide
        onClose={pickerOpen || creating ? () => {} : closeAdd}
        footer={
          <>
            <AppButton disabled={creating} onClick={closeAdd}>
              Cancel
            </AppButton>
            <AppButton
              variant="primary"
              type="submit"
              form="add-project-form"
              loading={creating}
              loadingLabel="Adding…"
              iconBefore={<Plus size={12} />}
            >
              Add project
            </AppButton>
          </>
        }
      >
        <form id="add-project-form" onSubmit={addProject}>
          {formError ? <div className="alert alert-error">{formError}</div> : null}
          <div className="field">
            <label htmlFor="project-name">Name</label>
            <Textfield
              id="project-name"
              value={name}
              onChange={(e) => setName(e.currentTarget.value)}
              placeholder="my-app"
              isDisabled={creating}
              isRequired
            />
          </div>
          <div className="field">
            <label htmlFor="project-path">Repository path</label>
            <div className="path-input-row">
              <Textfield
                id="project-path"
                value={repoPath}
                onChange={(e) => setRepoPath(e.currentTarget.value)}
                placeholder="Browse to a git checkout…"
                isDisabled={creating}
                isReadOnly
                onClick={() => setPickerOpen(true)}
                isRequired
              />
              <AppButton
                disabled={creating}
                onClick={() => setPickerOpen(true)}
                iconBefore={<FolderOpen size={12} />}
              >
                Browse
              </AppButton>
            </div>
          </div>
        </form>
      </ModalDialog>

      <DirectoryPicker
        open={pickerOpen}
        initialPath={repoPath || undefined}
        onClose={() => setPickerOpen(false)}
        onSelect={onPicked}
      />

      <ConfirmDialog
        open={Boolean(removeTarget)}
        title="Remove project?"
        confirmLabel="Remove project"
        danger
        busy={Boolean(removeTarget && busyId === removeTarget.id)}
        onClose={() => setRemoveTarget(null)}
        onConfirm={() => void confirmRemove()}
      >
        <p>
          Unregister <strong>{removeTarget?.name}</strong> from gojo. Scheduled work for this
          project stops, and gojo's local history for it is removed.
        </p>
        <p className="muted mt-3">
          This does <strong>not</strong> delete the git repository at{" "}
          <span className="mono">{removeTarget?.repoPath}</span>.
        </p>
      </ConfirmDialog>
    </div>
  );
}

// web/src/views/ProjectsView.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";

import {
  createProject,
  deleteProject,
  getProjectDoctor,
  listProjects,
  syncProject,
} from "@/api";
import ActionMenu, { type ActionMenuItem } from "@/components/ActionMenu.vue";
import AppButton from "@/components/AppButton.vue";
import ConfirmDialog from "@/components/ConfirmDialog.vue";
import DirectoryPicker from "@/components/DirectoryPicker.vue";
import ModalDialog from "@/components/ModalDialog.vue";
import SortableTh from "@/components/SortableTh.vue";
import TablePager from "@/components/TablePager.vue";
import { useLiveRefresh } from "@/composables/useLiveQuery";
import { useServerTable } from "@/composables/useServerTable";
import { type SortOrder } from "@/lib/pagination";
import HealthBadge from "@/components/status/HealthBadge.vue";
import {
  computeProjectHealth,
  type ProjectHealthSummary,
} from "@/lib/project-manifest";
import { FolderOpen, Plus } from "lucide-vue-next";
import type { Project } from "@/types";

const PROJECT_SORT_ALLOWED = ["name", "createdAt", "updatedAt", "defaultBranch"] as const;

const route = useRoute();
const router = useRouter();

function queryParam(key: string): string {
  const value = route.query[key];
  return typeof value === "string" ? value : "";
}

function initialSort(): string {
  const value = queryParam("sort");
  return (PROJECT_SORT_ALLOWED as readonly string[]).includes(value) ? value : "createdAt";
}

function initialOrder(): SortOrder {
  const value = queryParam("order");
  return value === "asc" || value === "desc" ? value : "asc";
}

const query = ref("");
const hasOpenPrs = ref(queryParam("hasOpenPrs") === "1" || queryParam("hasOpenPrs") === "true");
const busyId = ref<string | null>(null);
const addOpen = ref(false);
const creating = ref(false);
const pickerOpen = ref(false);
const name = ref("");
const repoPath = ref("");
const formError = ref("");
const notice = ref("");
const removeTarget = ref<Project | null>(null);
const healthById = ref<Record<string, ProjectHealthSummary>>({});
const healthLoading = ref(false);

const {
  page,
  pages,
  items: projects,
  total,
  loading,
  error,
  sort,
  order,
  setSort,
  rangeLabel,
  load,
} = useServerTable({
  defaultSort: initialSort(),
  defaultOrder: initialOrder(),
  watchSources: [query, hasOpenPrs],
  fetchPage: ({ limit, offset, sort: sortBy, order: sortOrder }) =>
    listProjects({
      limit,
      offset,
      sort: sortBy,
      order: sortOrder,
      q: query.value || undefined,
      ...(hasOpenPrs.value ? { hasOpenPrs: true } : {}),
    }),
});

watch([sort, order, hasOpenPrs], () => {
  const nextQuery = { ...route.query } as Record<string, string>;
  if (sort.value !== "createdAt" || order.value !== "asc") {
    nextQuery.sort = sort.value;
    nextQuery.order = order.value;
  } else {
    delete nextQuery.sort;
    delete nextQuery.order;
  }
  if (hasOpenPrs.value) {
    nextQuery.hasOpenPrs = "1";
  } else {
    delete nextQuery.hasOpenPrs;
  }
  const same =
    (nextQuery.sort ?? "") === queryParam("sort") &&
    (nextQuery.order ?? "") === queryParam("order") &&
    (nextQuery.hasOpenPrs ?? "") === queryParam("hasOpenPrs");
  if (!same) {
    void router.replace({ query: nextQuery });
  }
});

watch(
  () => route.query.hasOpenPrs,
  (value) => {
    const next = value === "1" || value === "true";
    if (hasOpenPrs.value !== next) {
      hasOpenPrs.value = next;
    }
  },
);

function basename(path: string): string {
  const trimmed = path.replace(/[/\\]+$/, "");
  const parts = trimmed.split(/[/\\]/);
  return parts[parts.length - 1] || "project";
}

function onPicked(path: string) {
  repoPath.value = path;
  if (!name.value.trim()) {
    name.value = basename(path);
  }
  pickerOpen.value = false;
}

function configSummary(project: Project): string {
  if (!project.hasManifest && project.agentCount === 0) {
    return "Not synced";
  }
  return `${project.enabledAgentCount}/${project.agentCount} agents · ${project.enabledScheduleCount}/${project.scheduleCount} schedules`;
}

function healthFor(project: Project): ProjectHealthSummary {
  return (
    healthById.value[project.id] ?? {
      score: null,
      level: project.hasManifest ? "warn" : "missing",
      label: project.hasManifest ? "…" : "No manifest",
    }
  );
}

function rowActions(project: Project): ActionMenuItem[] {
  return [
    {
      id: "open",
      label: "Open",
      to: { name: "project-detail", params: { id: project.id } },
    },
    {
      id: "sync",
      label: "Sync",
      disabled: busyId.value === project.id,
    },
    {
      id: "remove",
      label: "Remove",
      danger: true,
      disabled: busyId.value === project.id,
    },
  ];
}

async function refreshHealth(list: Project[]) {
  if (list.length === 0) {
    healthById.value = {};
    return;
  }
  healthLoading.value = true;
  const next: Record<string, ProjectHealthSummary> = { ...healthById.value };
  await Promise.all(
    list.map(async (project) => {
      try {
        const doctor = await getProjectDoctor(project.id);
        next[project.id] = computeProjectHealth(project, doctor);
      } catch {
        next[project.id] = {
          score: null,
          level: "warn",
          label: "Unavailable",
        };
      }
    }),
  );
  healthById.value = next;
  healthLoading.value = false;
}

function openAdd() {
  formError.value = "";
  addOpen.value = true;
}

function closeAdd() {
  if (creating.value || pickerOpen.value) {
    return;
  }
  addOpen.value = false;
  formError.value = "";
}

async function addProject() {
  if (!name.value.trim() || !repoPath.value.trim()) {
    formError.value = "Name and repository path are required";
    return;
  }
  creating.value = true;
  formError.value = "";
  notice.value = "";
  try {
    await createProject({ name: name.value.trim(), repoPath: repoPath.value.trim() });
    name.value = "";
    repoPath.value = "";
    addOpen.value = false;
    await load();
  } catch (err) {
    formError.value = err instanceof Error ? err.message : "Failed to create project";
  } finally {
    creating.value = false;
  }
}

async function sync(project: Project) {
  busyId.value = project.id;
  error.value = "";
  notice.value = "";
  try {
    const result = await syncProject(project.id);
    const leaf = result.sync.manifestPath
      ? result.sync.manifestPath.split(/[/\\]/).slice(-1)[0]
      : "no manifest";
    notice.value = `${project.name}: synced from ${leaf} — ${result.sync.profiles} profiles, ${result.sync.agents} agents, ${result.sync.schedules} schedules`;
    await load();
    const doctor = await getProjectDoctor(project.id);
    const refreshed = projects.value.find((row) => row.id === project.id) ?? result.project;
    healthById.value = {
      ...healthById.value,
      [project.id]: computeProjectHealth(refreshed, doctor),
    };
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Sync failed";
  } finally {
    busyId.value = null;
  }
}

function onAction(project: Project, actionId: string) {
  if (actionId === "sync") {
    void sync(project);
  } else if (actionId === "remove") {
    removeTarget.value = project;
  }
}

async function confirmRemove() {
  const project = removeTarget.value;
  if (!project) {
    return;
  }
  busyId.value = project.id;
  error.value = "";
  notice.value = "";
  try {
    await deleteProject(project.id);
    removeTarget.value = null;
    const { [project.id]: _removed, ...rest } = healthById.value;
    healthById.value = rest;
    await load();
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Remove failed";
  } finally {
    busyId.value = null;
  }
}

watch(
  projects,
  (list) => {
    void refreshHealth(list);
  },
  { deep: true },
);

useLiveRefresh({
  topics: ["projects", "impact", "work", "sources"],
  refresh: load,
});
</script>

<template>
  <div>
    <header class="page-header">
      <div>
        <h1>Projects</h1>
        <div class="subtitle">Registered repositories — sync manifests, check health, open details</div>
      </div>
      <div class="toolbar">
        <AppButton variant="primary" size="sm" :icon="Plus" @click="openAdd">Add project</AppButton>
      </div>
    </header>

    <div v-if="error" class="alert alert-error">{{ error }}</div>
    <div v-if="notice" class="alert alert-success">{{ notice }}</div>

    <div class="inline-form mb-7 task-filters">
      <div class="field flex-2">
        <label for="project-search">Search</label>
        <input
          id="project-search"
          v-model="query"
          class="input"
          type="search"
          placeholder="Name, path, id…"
        />
      </div>
      <div class="field">
        <label for="project-open-prs">Open PRs</label>
        <label class="checkbox-row" for="project-open-prs">
          <input id="project-open-prs" v-model="hasOpenPrs" type="checkbox" />
          Has open PRs
        </label>
      </div>
      <div class="field task-filter-count">
        <label>&nbsp;</label>
        <span class="muted">{{ total }} project{{ total === 1 ? "" : "s" }}</span>
      </div>
    </div>

    <div v-if="loading && projects.length === 0" class="empty">Loading projects…</div>
    <div v-else-if="total === 0" class="empty">
      {{
        query || hasOpenPrs
          ? "No projects match these filters"
          : "No projects yet — use Add project to register a repository"
      }}
    </div>
    <template v-else>
      <div class="table-wrap">
        <table class="data">
          <thead>
            <tr>
              <SortableTh column="name" label="Name" :sort="sort" :order="order" @sort="setSort" />
              <th>Repo path</th>
              <SortableTh
                column="defaultBranch"
                label="Branch"
                :sort="sort"
                :order="order"
                @sort="setSort"
              />
              <th>Config</th>
              <th>Open PRs</th>
              <th>
                Health
                <span v-if="healthLoading" class="muted text-sm"> …</span>
              </th>
              <SortableTh
                column="updatedAt"
                label="Updated"
                :sort="sort"
                :order="order"
                default-order="desc"
                @sort="setSort"
              />
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="project in projects" :key="project.id">
              <td>
                <RouterLink
                  :to="{ name: 'project-detail', params: { id: project.id } }"
                  class="entity-name"
                >
                  {{ project.name }}
                </RouterLink>
                <div class="mono muted text-sm">{{ project.id.slice(0, 10) }}…</div>
              </td>
              <td class="mono muted">{{ project.repoPath }}</td>
              <td class="mono">{{ project.defaultBranch }}</td>
              <td class="muted">{{ configSummary(project) }}</td>
              <td>
                <RouterLink
                  v-if="project.openPrCount > 0"
                  :to="{
                    name: 'project-detail',
                    params: { id: project.id },
                    hash: '#open-prs',
                  }"
                  class="entity-name"
                >
                  {{ project.openPrCount }}
                </RouterLink>
                <span v-else class="muted">—</span>
              </td>
              <td>
                <HealthBadge
                  :level="healthFor(project).level"
                  :label="healthFor(project).label"
                />
              </td>
              <td class="mono muted">{{ new Date(project.updatedAt).toLocaleString() }}</td>
              <td class="actions-cell">
                <ActionMenu
                  :items="rowActions(project)"
                  :disabled="busyId === project.id"
                  :label="`Actions for ${project.name}`"
                  @select="(id) => onAction(project, id)"
                />
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <TablePager
        v-model:page="page"
        :page-count="pages"
        :range-label="rangeLabel"
        :total="total"
      />
    </template>

    <ModalDialog
      :open="addOpen"
      title="Add project"
      wide
      :close-on-escape="!pickerOpen && !creating"
      :close-on-backdrop="!pickerOpen && !creating"
      @close="closeAdd"
    >
      <form id="add-project-form" @submit.prevent="addProject">
        <div v-if="formError" class="alert alert-error">{{ formError }}</div>
        <div class="field">
          <label for="project-name">Name</label>
          <input
            id="project-name"
            v-model="name"
            class="input"
            required
            placeholder="my-app"
            :disabled="creating"
          />
        </div>
        <div class="field">
          <label for="project-path">Repository path</label>
          <div class="path-input-row">
            <input
              id="project-path"
              v-model="repoPath"
              class="input"
              required
              readonly
              placeholder="Browse to a git checkout…"
              :disabled="creating"
              @click="pickerOpen = true"
            />
            <AppButton :icon="FolderOpen" :disabled="creating" @click="pickerOpen = true">
              Browse
            </AppButton>
          </div>
        </div>
      </form>
      <template #footer>
        <AppButton :disabled="creating" @click="closeAdd">Cancel</AppButton>
        <AppButton
          variant="primary"
          :icon="Plus"
          type="submit"
          form="add-project-form"
          :loading="creating"
          loading-label="Adding…"
        >
          Add project
        </AppButton>
      </template>
    </ModalDialog>

    <DirectoryPicker
      :open="pickerOpen"
      :initial-path="repoPath || undefined"
      @close="pickerOpen = false"
      @select="onPicked"
    />

    <ConfirmDialog
      :open="Boolean(removeTarget)"
      title="Remove project?"
      confirm-label="Remove project"
      danger
      :busy="Boolean(removeTarget && busyId === removeTarget.id)"
      @close="removeTarget = null"
      @confirm="confirmRemove"
    >
      <p>
        Unregister <strong>{{ removeTarget?.name }}</strong> from gojo. Scheduled work for this
        project stops, and gojo’s local history for it is removed.
      </p>
      <p class="muted mt-3">
        This does <strong>not</strong> delete the git repository at
        <span class="mono">{{ removeTarget?.repoPath }}</span>.
      </p>
    </ConfirmDialog>
  </div>
</template>
