// web/src/components/DirectoryPicker.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { Check, FolderOpen, X } from "lucide-vue-next";

import AppButton from "@/components/AppButton.vue";

import { browseFilesystem } from "@/api";
import type { BrowseRoot, DirectoryListing } from "@/types";

const props = defineProps<{
  open: boolean;
  initialPath?: string;
}>();

const emit = defineEmits<{
  close: [];
  select: [path: string];
}>();

const listing = ref<DirectoryListing | null>(null);
const roots = ref<BrowseRoot[]>([]);
const loading = ref(false);
const error = ref("");
const selected = ref<string | null>(null);

async function load(path?: string) {
  loading.value = true;
  error.value = "";
  try {
    const result = await browseFilesystem(path);
    listing.value = result.listing;
    roots.value = result.roots;
    selected.value = result.listing.isGitRepo ? result.listing.path : null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to browse filesystem";
  } finally {
    loading.value = false;
  }
}

function openEntry(path: string) {
  void load(path);
}

function chooseCurrent() {
  if (!listing.value) {
    return;
  }
  emit("select", selected.value ?? listing.value.path);
}

function onKeydown(event: KeyboardEvent) {
  if (event.key === "Escape") {
    emit("close");
  }
}

watch(
  () => props.open,
  (isOpen) => {
    if (isOpen) {
      selected.value = null;
      void load(props.initialPath);
    }
  },
);

onMounted(() => {
  if (props.open) {
    void load(props.initialPath);
  }
});
</script>

<template>
  <div
    v-if="open"
    class="picker-backdrop"
    role="dialog"
    aria-modal="true"
    aria-label="Choose repository directory"
    @keydown="onKeydown"
  >
    <div class="picker">
      <header class="picker-header">
        <div>
          <div class="picker-title">Choose repository</div>
          <div class="picker-path mono">{{ listing?.path ?? "…" }}</div>
        </div>
        <AppButton size="sm" :icon="X" @click="emit('close')">Close</AppButton>
      </header>

      <div class="picker-roots">
        <AppButton
          v-for="root in roots"
          :key="root.path"
          size="sm"
          :icon="FolderOpen"
          @click="openEntry(root.path)"
        >
          {{ root.label }}
        </AppButton>
      </div>

      <div v-if="error" class="alert alert-error">{{ error }}</div>

      <div class="picker-body">
        <button
          v-if="listing?.parent"
          class="picker-row"
          type="button"
          @click="openEntry(listing.parent)"
        >
          <span class="picker-icon">↑</span>
          <span>.. parent</span>
        </button>

        <div v-if="loading" class="empty">Loading…</div>
        <template v-else-if="listing">
          <button
            v-for="entry in listing.entries"
            :key="entry.path"
            class="picker-row"
            :class="{ selected: selected === entry.path, git: entry.isGitRepo }"
            type="button"
            @click="selected = entry.path"
            @dblclick="openEntry(entry.path)"
          >
            <span class="picker-icon">{{ entry.isGitRepo ? "●" : "▸" }}</span>
            <span class="picker-name">{{ entry.name }}</span>
            <span v-if="entry.isGitRepo" class="picker-badge">git</span>
            <span class="picker-open muted" @click.stop="openEntry(entry.path)">Open</span>
          </button>
          <div v-if="listing.entries.length === 0" class="empty">No subdirectories</div>
        </template>
      </div>

      <footer class="picker-footer">
        <div class="muted">
          <template v-if="selected">Selected: <span class="mono">{{ selected }}</span></template>
          <template v-else-if="listing?.isGitRepo">
            Current folder is a git repo — you can select it
          </template>
          <template v-else>Select a folder, or open into one (double-click)</template>
        </div>
        <div class="picker-actions">
          <AppButton :icon="X" @click="emit('close')">Cancel</AppButton>
          <AppButton
            variant="primary"
            :icon="Check"
            :disabled="!listing"
            @click="chooseCurrent"
          >
            Use this folder
          </AppButton>
        </div>
      </footer>
    </div>
  </div>
</template>

// web/src/contexts/operations/components/DirectoryPicker.tsx
import { useCallback, useEffect, useState } from "react";
import { Check, FolderOpen, X } from "lucide-react";

import { AppButton } from "@/ui/AppButton";
import { ModalDialog } from "@/ui/ModalDialog";
import { browseFilesystem } from "@/contexts/operations/contract";
import type { BrowseRoot, DirectoryListing } from "@/contexts/operations/types";

export type DirectoryPickerProps = {
  open: boolean;
  initialPath?: string;
  onClose: () => void;
  onSelect: (path: string) => void;
};

export function DirectoryPicker({ open, initialPath, onClose, onSelect }: DirectoryPickerProps) {
  const [listing, setListing] = useState<DirectoryListing | null>(null);
  const [roots, setRoots] = useState<BrowseRoot[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [selected, setSelected] = useState<string | null>(null);

  const load = useCallback(async (path?: string) => {
    setLoading(true);
    setError("");
    try {
      const result = await browseFilesystem(path);
      setListing(result.listing);
      setRoots(result.roots);
      setSelected(result.listing.isGitRepo ? result.listing.path : null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to browse filesystem");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (open) {
      setSelected(null);
      void load(initialPath);
    }
  }, [open, initialPath, load]);

  function chooseCurrent() {
    if (!listing) return;
    onSelect(selected ?? listing.path);
  }

  return (
    <ModalDialog
      open={open}
      title="Choose repository"
      wide
      onClose={onClose}
      footer={
        <>
          <AppButton onClick={onClose} iconBefore={<X size={12} />}>
            Cancel
          </AppButton>
          <AppButton
            variant="primary"
            disabled={!listing}
            onClick={chooseCurrent}
            iconBefore={<Check size={12} />}
          >
            Use this folder
          </AppButton>
        </>
      }
    >
      <div className="picker-path mono mb-3">{listing?.path ?? "…"}</div>

      <div className="picker-roots">
        {roots.map((root) => (
          <AppButton
            key={root.path}
            size="sm"
            onClick={() => void load(root.path)}
            iconBefore={<FolderOpen size={12} />}
          >
            {root.label}
          </AppButton>
        ))}
      </div>

      {error ? <div className="alert alert-error">{error}</div> : null}

      <div className="picker-body">
        {listing?.parent ? (
          <button className="picker-row" type="button" onClick={() => void load(listing.parent!)}>
            <span className="picker-icon">↑</span>
            <span>.. parent</span>
          </button>
        ) : null}

        {loading ? (
          <div className="empty">Loading…</div>
        ) : listing ? (
          <>
            {listing.entries.map((entry) => (
              <button
                key={entry.path}
                className={`picker-row${selected === entry.path ? " selected" : ""}${entry.isGitRepo ? " git" : ""}`}
                type="button"
                onClick={() => setSelected(entry.path)}
                onDoubleClick={() => void load(entry.path)}
              >
                <span className="picker-icon">{entry.isGitRepo ? "●" : "▸"}</span>
                <span className="picker-name">{entry.name}</span>
                {entry.isGitRepo ? <span className="picker-badge">git</span> : null}
                <span
                  className="picker-open muted"
                  onClick={(e) => {
                    e.stopPropagation();
                    void load(entry.path);
                  }}
                >
                  Open
                </span>
              </button>
            ))}
            {listing.entries.length === 0 ? <div className="empty">No subdirectories</div> : null}
          </>
        ) : null}
      </div>

      <div className="muted mt-3">
        {selected ? (
          <>
            Selected: <span className="mono">{selected}</span>
          </>
        ) : listing?.isGitRepo ? (
          "Current folder is a git repo — you can select it"
        ) : (
          "Select a folder, or open into one (double-click)"
        )}
      </div>
    </ModalDialog>
  );
}
