// web/src/ui/MetricDelta.tsx
import { Minus, TrendingDown, TrendingUp } from "lucide-react";

import { UiIcon } from "@/ui/UiIcon";
import { deltaTone, formatDelta, type MetricDirection } from "@/kernel/stat-metrics";
import { badgeToneClass } from "@/kernel/status-icons";

export type MetricDeltaProps = {
  delta: number | null;
  direction: MetricDirection;
  title?: string;
};

export function MetricDelta({ delta, direction, title }: MetricDeltaProps) {
  if (delta === null) return null;
  const toneClass = badgeToneClass(deltaTone({ direction }, delta));
  const Icon = delta === 0 ? Minus : delta > 0 ? TrendingUp : TrendingDown;
  const label = formatDelta(delta);

  return (
    <span
      className={`metric-delta ${toneClass}`}
      title={title}
      aria-label={title ? `${label} ${title}` : label}
    >
      <UiIcon icon={Icon} size={12} />
      <span className="metric-delta__value">{label}</span>
    </span>
  );
}

// web/src/ui/MetricDelta.vue
<script setup lang="ts">
import { computed } from "vue";
import { Minus, TrendingDown, TrendingUp } from "lucide-vue-next";

import UiIcon from "@/ui/UiIcon.vue";
import { deltaTone, formatDelta, type MetricDirection } from "@/kernel/stat-metrics";
import { badgeToneClass } from "@/kernel/status-icons";

const props = defineProps<{
  delta: number | null;
  direction: MetricDirection;
  title?: string;
}>();

const visible = computed(() => props.delta !== null);

const toneClass = computed(() => badgeToneClass(deltaTone({ direction: props.direction }, props.delta)));

const trendIcon = computed(() => {
  if (props.delta === null || props.delta === 0) {
    return Minus;
  }
  return props.delta > 0 ? TrendingUp : TrendingDown;
});
</script>

<template>
  <span
    v-if="visible"
    class="metric-delta"
    :class="toneClass"
    :title="title"
    :aria-label="title ? `${formatDelta(delta)} ${title}` : formatDelta(delta)"
  >
    <UiIcon :icon="trendIcon" :size="12" />
    <span class="metric-delta__value">{{ formatDelta(delta) }}</span>
  </span>
</template>
