// web/src/components/RunActivityFeed.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";

import AppButton from "@/components/AppButton.vue";
import TablePager from "@/components/TablePager.vue";
import { useClientPager } from "@/composables/useClientPager";
import { fmtDuration, fmtTime } from "@/lib/format";
import {
  buildActivityItems,
  type ActivityItem,
  type ActivityKind,
} from "@/lib/run-activity";
import type { PhaseKey } from "@/lib/run-phases";
import type { RunEvent } from "@/types";

const props = defineProps<{
  events: RunEvent[];
  phaseFilter?: PhaseKey | null;
  highlightId?: string | null;
}>();

const PAGE_SIZE = 10;

const kindFilter = ref<ActivityKind | "all">("all");
const query = ref("");
const expanded = ref<Record<string, boolean>>({});

const allItems = computed(() => buildActivityItems(props.events));

const filtered = computed(() => {
  const q = query.value.trim().toLowerCase();
  return allItems.value.filter((item) => {
    if (props.phaseFilter && item.phase !== props.phaseFilter) {
      return false;
    }
    if (kindFilter.value !== "all" && item.kind !== kindFilter.value) {
      return false;
    }
    if (!q) {
      return true;
    }
    if (
      item.title.toLowerCase().includes(q) ||
      (item.detail?.toLowerCase().includes(q) ?? false) ||
      (item.body?.toLowerCase().includes(q) ?? false)
    ) {
      return true;
    }
    return (
      item.tools?.some(
        (tool) =>
          tool.name.toLowerCase().includes(q) ||
          (tool.summary?.toLowerCase().includes(q) ?? false),
      ) ?? false
    );
  });
});

const { page, pages, pageItems, total, sort, order, setSort, rangeLabel, reset } = useClientPager(
  filtered,
  PAGE_SIZE,
  { defaultSort: "at", defaultOrder: "desc" },
);

// Auto-expand the newest assistant/stderr message so live thinking is visible.
watch(
  pageItems,
  (rows) => {
    const newest = rows.find((row) => row.kind === "assistant" || row.body);
    if (newest && expanded.value[newest.id] === undefined) {
      expanded.value = { ...expanded.value, [newest.id]: true };
    }
  },
  { immediate: true },
);

watch([() => props.phaseFilter, kindFilter, query], () => {
  reset();
});

watch(
  () => props.highlightId,
  (id) => {
    if (!id) {
      return;
    }
    const index = filtered.value.findIndex((item) => item.id === id);
    if (index >= 0) {
      page.value = Math.floor(index / PAGE_SIZE) + 1;
      expanded.value = { ...expanded.value, [id]: true };
    }
  },
);

function toggle(id: string) {
  expanded.value = { ...expanded.value, [id]: !expanded.value[id] };
}

function statusClass(item: ActivityItem): string {
  return `kind-${item.status ?? "info"}`;
}
</script>

<template>
  <div class="activity-panel">
    <div class="filter-bar activity-filters">
      <select v-model="kindFilter" class="select" aria-label="Kind">
        <option value="all">All kinds</option>
        <option value="lifecycle">Lifecycle</option>
        <option value="agent">Agent</option>
        <option value="assistant">Assistant</option>
        <option value="tool">Tools</option>
        <option value="validation">Validation</option>
        <option value="artifact">Artifacts</option>
        <option value="error">Errors</option>
      </select>
      <input
        v-model="query"
        class="input filter-bar-search"
        type="search"
        placeholder="Filter activity…"
        aria-label="Search"
      />
      <span class="muted filter-bar-count">{{ total }} events</span>
      <div class="activity-sort" role="group" aria-label="Sort activity">
        <AppButton
          variant="ghost"
          size="sm"
          :selected="sort === 'at'"
          @click="setSort('at', 'desc')"
        >
          Time {{ sort === "at" ? (order === "asc" ? "↑" : "↓") : "" }}
        </AppButton>
        <AppButton
          variant="ghost"
          size="sm"
          :selected="sort === 'kind'"
          @click="setSort('kind', 'asc')"
        >
          Kind {{ sort === "kind" ? (order === "asc" ? "↑" : "↓") : "" }}
        </AppButton>
        <AppButton
          variant="ghost"
          size="sm"
          :selected="sort === 'title'"
          @click="setSort('title', 'asc')"
        >
          Title {{ sort === "title" ? (order === "asc" ? "↑" : "↓") : "" }}
        </AppButton>
      </div>
    </div>

    <ul v-if="pageItems.length" class="activity-feed">
      <li
        v-for="row in pageItems"
        :id="`activity-${row.id}`"
        :key="row.id"
        class="activity-row"
        :class="[statusClass(row), { highlighted: highlightId === row.id }]"
      >
        <span class="time">{{ fmtTime(row.at) }}</span>
        <div class="activity-body">
          <div class="activity-title">{{ row.title }}</div>
          <div v-if="row.detail" class="activity-detail muted">{{ row.detail }}</div>

          <template v-if="row.body">
            <AppButton variant="ghost" size="sm" class="mt-2" @click="toggle(row.id)">
              {{ expanded[row.id] ? "Hide message" : "Show message" }}
            </AppButton>
            <pre
              v-if="expanded[row.id]"
              class="pre-block mt-2 activity-assistant-body"
              >{{ row.body }}</pre
            >
          </template>

          <template v-if="row.tools?.length">
            <AppButton variant="ghost" size="sm" class="mt-2" @click="toggle(row.id)">
              {{
                expanded[row.id]
                  ? "Hide tools"
                  : row.tools.length === 1
                    ? "Show tool"
                    : `Show ${row.tools.length} tools`
              }}
            </AppButton>
            <ul v-if="expanded[row.id]" class="tool-list mt-2">
              <li v-for="tool in row.tools" :key="tool.callId" class="tool-list-item">
                <span class="tool-name mono">{{ tool.name }}</span>
                <span
                  class="tool-phase muted"
                  :class="tool.phase === 'completed' ? 'tool-done' : ''"
                  >{{ tool.phase === "completed" ? "done" : "running" }}</span
                >
                <span v-if="tool.summary" class="tool-summary muted">{{ tool.summary }}</span>
              </li>
            </ul>
          </template>

          <template v-if="row.validation">
            <div class="activity-meta mono muted">
              {{ row.validation.command }} · {{ fmtDuration(row.validation.durationMs) }}
            </div>
            <AppButton variant="ghost" size="sm" class="mt-2" @click="toggle(row.id)">
              {{ expanded[row.id] ? "Hide output" : "Show output" }}
            </AppButton>
            <div v-if="expanded[row.id]" class="validation-output mt-2">
              <pre v-if="row.validation.stdout" class="pre-block">{{ row.validation.stdout }}</pre>
              <pre v-if="row.validation.stderr" class="pre-block pre-stderr">{{
                row.validation.stderr
              }}</pre>
              <div
                v-if="!row.validation.stdout && !row.validation.stderr"
                class="muted"
              >
                No stdout/stderr captured for this step.
              </div>
            </div>
          </template>
        </div>
      </li>
    </ul>
    <div v-else class="muted">No activity matches this filter.</div>

    <TablePager
      v-model:page="page"
      :page-count="pages"
      :range-label="rangeLabel"
      :total="total"
    />
  </div>
</template>

// web/src/ui/RunActivityFeed.tsx
import { useEffect, useMemo, useState } from "react";
import { AppSelect as Select } from "@/ui/AppSelect";
import { AppTextfield as Textfield } from "@/ui/AppTextfield";

import { AppButton } from "@/ui/AppButton";
import { SegmentedControl } from "@/ui/SegmentedControl";
import { TablePager } from "@/ui/TablePager";
import { useClientPager } from "@/platform/useClientPager";
import { fmtDuration, fmtTime } from "@/kernel/format";
import {
  buildActivityItems,
  type ActivityItem,
  type ActivityKind,
} from "@/kernel/run-activity";
import type { PhaseKey } from "@/kernel/run-phases";
import type { RunEvent } from "@/contexts/execution/types";

const PAGE_SIZE = 10;

type SortField = "at" | "kind" | "title";
type Order = "asc" | "desc";

const KIND_OPTIONS: Array<{ value: ActivityKind | "all"; label: string }> = [
  { value: "all", label: "All kinds" },
  { value: "lifecycle", label: "Lifecycle" },
  { value: "agent", label: "Agent" },
  { value: "assistant", label: "Assistant" },
  { value: "tool", label: "Tools" },
  { value: "validation", label: "Validation" },
  { value: "artifact", label: "Artifacts" },
  { value: "error", label: "Errors" },
];

export type RunActivityFeedProps = {
  events: RunEvent[];
  phaseFilter?: PhaseKey | null;
  highlightId?: string | null;
};

export function RunActivityFeed({ events, phaseFilter, highlightId }: RunActivityFeedProps) {
  const [kindFilter, setKindFilter] = useState<ActivityKind | "all">("all");
  const [query, setQuery] = useState("");
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [sort, setSort] = useState<SortField>("at");
  const [order, setOrder] = useState<Order>("desc");

  const allItems = useMemo(() => buildActivityItems(events), [events]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return allItems.filter((item) => {
      if (phaseFilter && item.phase !== phaseFilter) return false;
      if (kindFilter !== "all" && item.kind !== kindFilter) return false;
      if (!q) return true;
      if (
        item.title.toLowerCase().includes(q) ||
        (item.detail?.toLowerCase().includes(q) ?? false) ||
        (item.body?.toLowerCase().includes(q) ?? false)
      ) {
        return true;
      }
      return (
        item.tools?.some(
          (tool) =>
            tool.name.toLowerCase().includes(q) ||
            (tool.summary?.toLowerCase().includes(q) ?? false),
        ) ?? false
      );
    });
  }, [allItems, kindFilter, phaseFilter, query]);

  const sorted = useMemo(() => {
    const arr = [...filtered];
    arr.sort((a, b) => {
      let cmp = 0;
      if (sort === "at") cmp = a.atMs - b.atMs;
      else if (sort === "kind") cmp = a.kind.localeCompare(b.kind);
      else cmp = a.title.localeCompare(b.title);
      return order === "asc" ? cmp : -cmp;
    });
    return arr;
  }, [filtered, sort, order]);

  const pager = useClientPager(sorted, PAGE_SIZE);

  useEffect(() => {
    pager.setPage(0);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phaseFilter, kindFilter, query, sort, order]);

  useEffect(() => {
    const newest = pager.items.find((row) => row.kind === "assistant" || row.body);
    if (newest && expanded[newest.id] === undefined) {
      setExpanded((prev) => ({ ...prev, [newest.id]: true }));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pager.items]);

  useEffect(() => {
    if (!highlightId) return;
    const idx = sorted.findIndex((item) => item.id === highlightId);
    if (idx < 0) return;
    pager.setPage(Math.floor(idx / PAGE_SIZE));
    setExpanded((prev) => ({ ...prev, [highlightId]: true }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [highlightId, sorted]);

  function toggle(id: string) {
    setExpanded((prev) => ({ ...prev, [id]: !prev[id] }));
  }

  function statusClass(item: ActivityItem): string {
    return `kind-${item.status ?? "info"}`;
  }

  function toggleSort(next: SortField, first: Order) {
    if (sort === next) {
      setOrder((o) => (o === "asc" ? "desc" : "asc"));
    } else {
      setSort(next);
      setOrder(first);
    }
  }

  const kindValue = KIND_OPTIONS.find((o) => o.value === kindFilter) ?? KIND_OPTIONS[0];

  return (
    <div className="activity-panel">
      <div className="filter-bar activity-filters">
        <div style={{ minWidth: 180 }}>
          <Select
            inputId="activity-kind"
            aria-label="Kind"
            value={kindValue}
            options={KIND_OPTIONS}
            onChange={(opt) => setKindFilter((opt?.value as ActivityKind | "all") ?? "all")}
            isSearchable={false}
          />
        </div>
        <div style={{ minWidth: 220, flex: 1 }}>
          <Textfield
            value={query}
            onChange={(e) => setQuery(e.currentTarget.value)}
            placeholder="Filter activity…"
            aria-label="Search"
            type="search"
          />
        </div>
        <span className="muted filter-bar-count">{sorted.length} events</span>
        <SegmentedControl
          ariaLabel="Sort activity"
          value={sort}
          onChange={(next) => {
            const first: Order = next === "at" ? "desc" : "asc";
            toggleSort(next, first);
          }}
          items={[
            {
              value: "at",
              label: `Time${sort === "at" ? (order === "asc" ? " ↑" : " ↓") : ""}`,
            },
            {
              value: "kind",
              label: `Kind${sort === "kind" ? (order === "asc" ? " ↑" : " ↓") : ""}`,
            },
            {
              value: "title",
              label: `Title${sort === "title" ? (order === "asc" ? " ↑" : " ↓") : ""}`,
            },
          ]}
        />
      </div>

      {pager.items.length ? (
        <ul className="activity-feed">
          {pager.items.map((row) => (
            <li
              key={row.id}
              id={`activity-${row.id}`}
              className={`activity-row ${statusClass(row)}${highlightId === row.id ? " highlighted" : ""}`}
            >
              <span className="time">{fmtTime(row.at)}</span>
              <div className="activity-body">
                <div className="activity-title">{row.title}</div>
                {row.detail ? <div className="activity-detail muted">{row.detail}</div> : null}

                {row.body ? (
                  <>
                    <AppButton
                      variant="ghost"
                      size="sm"
                      className="mt-2"
                      onClick={() => toggle(row.id)}
                    >
                      {expanded[row.id] ? "Hide message" : "Show message"}
                    </AppButton>
                    {expanded[row.id] ? (
                      <pre className="pre-block mt-2 activity-assistant-body">{row.body}</pre>
                    ) : null}
                  </>
                ) : null}

                {row.tools?.length ? (
                  <>
                    <AppButton
                      variant="ghost"
                      size="sm"
                      className="mt-2"
                      onClick={() => toggle(row.id)}
                    >
                      {expanded[row.id]
                        ? "Hide tools"
                        : row.tools.length === 1
                          ? "Show tool"
                          : `Show ${row.tools.length} tools`}
                    </AppButton>
                    {expanded[row.id] ? (
                      <ul className="tool-list mt-2">
                        {row.tools.map((tool) => (
                          <li key={tool.callId} className="tool-list-item">
                            <span className="tool-name mono">{tool.name}</span>
                            <span
                              className={`tool-phase muted${tool.phase === "completed" ? " tool-done" : ""}`}
                            >
                              {tool.phase === "completed" ? "done" : "running"}
                            </span>
                            {tool.summary ? (
                              <span className="tool-summary muted">{tool.summary}</span>
                            ) : null}
                          </li>
                        ))}
                      </ul>
                    ) : null}
                  </>
                ) : null}

                {row.validation ? (
                  <>
                    <div className="activity-meta mono muted">
                      {row.validation.command} · {fmtDuration(row.validation.durationMs)}
                    </div>
                    <AppButton
                      variant="ghost"
                      size="sm"
                      className="mt-2"
                      onClick={() => toggle(row.id)}
                    >
                      {expanded[row.id] ? "Hide output" : "Show output"}
                    </AppButton>
                    {expanded[row.id] ? (
                      <div className="validation-output mt-2">
                        {row.validation.stdout ? (
                          <pre className="pre-block">{row.validation.stdout}</pre>
                        ) : null}
                        {row.validation.stderr ? (
                          <pre className="pre-block pre-stderr">{row.validation.stderr}</pre>
                        ) : null}
                        {!row.validation.stdout && !row.validation.stderr ? (
                          <div className="muted">
                            No stdout/stderr captured for this step.
                          </div>
                        ) : null}
                      </div>
                    ) : null}
                  </>
                ) : null}
              </div>
            </li>
          ))}
        </ul>
      ) : (
        <div className="muted">No activity matches this filter.</div>
      )}

      <TablePager
        offset={pager.offset}
        limit={PAGE_SIZE}
        total={sorted.length}
        onPrev={pager.prev}
        onNext={pager.next}
      />
    </div>
  );
}
