// web/src/ui/StatusBadge.vue
<script setup lang="ts">
import type { Component } from "vue";

import UiIcon from "@/ui/UiIcon.vue";
import { badgeToneClass, type BadgeTone } from "@/kernel/status-icons";

withDefaults(
  defineProps<{
    label: string;
    icon: Component;
    tone?: BadgeTone;
    showLabel?: boolean;
  }>(),
  {
    tone: "neutral",
    showLabel: true,
  },
);
</script>

<template>
  <span
    class="badge"
    :class="[badgeToneClass(tone), { 'badge--icon-only': !showLabel }]"
    :aria-label="label"
    :title="label"
  >
    <UiIcon :icon="icon" class="badge__icon" :size="12" />
    <span v-if="showLabel" class="badge__label">{{ label }}</span>
  </span>
</template>

// web/src/ui/StatusBadge.tsx
import { toneIcon, type BadgeTone } from "@/kernel/status-icons";
import { UiIcon } from "@/ui/UiIcon";

export type StatusBadgeProps = {
  tone: BadgeTone;
  label: string;
};

/**
 * Neutral pill with a tone-colored icon.
 *
 * Deliberately not `@atlaskit/lozenge`: the legacy lozenge hardcodes theme-blind
 * fills (e.g. success `#b3df72`), and the newer lozenge ties icon color to the
 * pill tint — neither can render “neutral surface + semantic icon.”
 */
export function StatusBadge({ tone, label }: StatusBadgeProps) {
  return (
    <span className={`badge badge-neutral badge--tone-${tone}`}>
      <span className="badge__icon" aria-hidden="true">
        <UiIcon icon={toneIcon(tone)} size={12} />
      </span>
      <span className="badge__label">{label}</span>
    </span>
  );
}
