// web/src/contexts/execution/components/RunActivitySection.vue
<script setup lang="ts">
import type { PhaseKey } from "@/kernel/run-phases";
import type { RunEvent } from "@/contexts/execution/types";
import AppButton from "@/ui/AppButton.vue";
import RunActivityFeed from "@/ui/RunActivityFeed.vue";
import RunTimelineChart from "@/ui/RunTimelineChart.vue";

defineProps<{
  events: RunEvent[];
  selectedPhase: PhaseKey | null;
  highlightActivityId: string | null;
}>();

const emit = defineEmits<{
  "update:selectedPhase": [value: PhaseKey | null];
  "update:highlightActivityId": [value: string | null];
}>();
</script>

<template>
  <section class="panel">
    <div class="panel-header">Timeline</div>
    <div class="panel-body">
      <RunTimelineChart
        :events="events"
        :selected-phase="selectedPhase"
        @select-phase="emit('update:selectedPhase', $event)"
        @select-activity="emit('update:highlightActivityId', $event)"
      />
    </div>
  </section>

  <section class="panel">
    <div class="panel-header">
      Activity
      <AppButton
        v-if="selectedPhase"
        size="sm"
        @click="emit('update:selectedPhase', null)"
      >
        Clear phase filter
      </AppButton>
    </div>
    <div class="panel-body">
      <RunActivityFeed
        :events="events"
        :phase-filter="selectedPhase"
        :highlight-id="highlightActivityId"
      />
    </div>
  </section>
</template>

// web/src/contexts/execution/components/RunActivitySection.tsx
import type { PhaseKey } from "@/kernel/run-phases";
import type { RunEvent } from "@/contexts/execution/types";
import { AppButton } from "@/ui/AppButton";
import { RunActivityFeed } from "@/ui/RunActivityFeed";
import { RunTimelineChart } from "@/ui/RunTimelineChart";

export type RunActivitySectionProps = {
  events: RunEvent[];
  selectedPhase: PhaseKey | null;
  highlightActivityId: string | null;
  onSelectedPhaseChange: (value: PhaseKey | null) => void;
  onHighlightActivityIdChange: (value: string | null) => void;
};

export function RunActivitySection({
  events,
  selectedPhase,
  highlightActivityId,
  onSelectedPhaseChange,
  onHighlightActivityIdChange,
}: RunActivitySectionProps) {
  return (
    <>
      <section className="panel">
        <div className="panel-header">Timeline</div>
        <div className="panel-body">
          <RunTimelineChart
            events={events}
            selectedPhase={selectedPhase}
            onSelectPhase={onSelectedPhaseChange}
            onSelectActivity={onHighlightActivityIdChange}
          />
        </div>
      </section>

      <section className="panel">
        <div className="panel-header">
          Activity
          {selectedPhase ? (
            <AppButton size="sm" onClick={() => onSelectedPhaseChange(null)}>
              Clear phase filter
            </AppButton>
          ) : null}
        </div>
        <div className="panel-body">
          <RunActivityFeed
            events={events}
            phaseFilter={selectedPhase}
            highlightId={highlightActivityId}
          />
        </div>
      </section>
    </>
  );
}
