// web/src/views/ImpactView.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";

import { listImpactItems, listProjects } from "@/api";
import PageHeader from "@/components/PageHeader.vue";
import SortableTh from "@/components/SortableTh.vue";
import TablePager from "@/components/TablePager.vue";
import UiIcon from "@/components/UiIcon.vue";
import VerificationBadge from "@/components/status/VerificationBadge.vue";
import { useLiveRefresh } from "@/composables/useLiveQuery";
import { useServerTable } from "@/composables/useServerTable";
import { MAX_PAGE_LIMIT, type SortOrder } from "@/lib/pagination";
import {
  IMPACT_CATEGORIES,
  impactCategoryLabel,
  impactCategorySpec,
} from "@/lib/stat-metrics";
import type { Project } from "@/types";

const IMPACT_SORT_ALLOWED = [
  "createdAt",
  "category",
  "subject",
  "projectName",
  "agentName",
] as const;

const route = useRoute();
const router = useRouter();

function queryParam(key: string): string {
  const value = route.query[key];
  return typeof value === "string" ? value : "";
}

function initialSort(): string {
  const value = queryParam("sort");
  return (IMPACT_SORT_ALLOWED as readonly string[]).includes(value) ? value : "createdAt";
}

function initialOrder(): SortOrder {
  const value = queryParam("order");
  return value === "asc" || value === "desc" ? value : "desc";
}

const projects = ref<Project[]>([]);
const categoryFilter = ref(queryParam("category"));
const projectFilter = ref(queryParam("projectId"));
const fromFilter = ref(queryParam("from"));
const toFilter = ref(queryParam("to"));
const rangeFilter = ref(queryParam("range"));

const categoryOptions = computed(() =>
  IMPACT_CATEGORIES.map((category) => ({
    value: category,
    label: impactCategoryLabel(category),
  })),
);

const {
  page,
  pages,
  items,
  total,
  loading,
  error,
  sort,
  order,
  setSort,
  rangeLabel,
  load,
} = useServerTable({
  defaultSort: initialSort(),
  defaultOrder: initialOrder(),
  watchSources: [categoryFilter, projectFilter, fromFilter, toFilter],
  fetchPage: ({ limit, offset, sort: sortBy, order: sortOrder }) =>
    listImpactItems({
      limit,
      offset,
      sort: sortBy,
      order: sortOrder,
      category: categoryFilter.value || undefined,
      projectId: projectFilter.value || undefined,
      from: fromFilter.value || undefined,
      to: toFilter.value || undefined,
    }),
});

async function loadProjects() {
  const result = await listProjects({ limit: MAX_PAGE_LIMIT, offset: 0 });
  projects.value = result.items;
}

function formatWhen(value: string): string {
  try {
    return new Date(value).toLocaleString();
  } catch {
    return value;
  }
}

watch(
  () =>
    [
      route.query.category,
      route.query.projectId,
      route.query.from,
      route.query.to,
      route.query.range,
    ] as const,
  ([category, projectId, from, to, range]) => {
    const nextCategory = typeof category === "string" ? category : "";
    const nextProject = typeof projectId === "string" ? projectId : "";
    const nextFrom = typeof from === "string" ? from : "";
    const nextTo = typeof to === "string" ? to : "";
    const nextRange = typeof range === "string" ? range : "";
    if (categoryFilter.value !== nextCategory) categoryFilter.value = nextCategory;
    if (projectFilter.value !== nextProject) projectFilter.value = nextProject;
    if (fromFilter.value !== nextFrom) fromFilter.value = nextFrom;
    if (toFilter.value !== nextTo) toFilter.value = nextTo;
    if (rangeFilter.value !== nextRange) rangeFilter.value = nextRange;
  },
);

watch([categoryFilter, projectFilter, fromFilter, toFilter, rangeFilter, sort, order], () => {
  const nextQuery = { ...route.query } as Record<string, string>;
  if (categoryFilter.value) nextQuery.category = categoryFilter.value;
  else delete nextQuery.category;
  if (projectFilter.value) nextQuery.projectId = projectFilter.value;
  else delete nextQuery.projectId;
  if (fromFilter.value) nextQuery.from = fromFilter.value;
  else delete nextQuery.from;
  if (toFilter.value) nextQuery.to = toFilter.value;
  else delete nextQuery.to;
  if (rangeFilter.value) nextQuery.range = rangeFilter.value;
  else delete nextQuery.range;
  if (sort.value !== "createdAt" || order.value !== "desc") {
    nextQuery.sort = sort.value;
    nextQuery.order = order.value;
  } else {
    delete nextQuery.sort;
    delete nextQuery.order;
  }
  const same =
    (nextQuery.category ?? "") === queryParam("category") &&
    (nextQuery.projectId ?? "") === queryParam("projectId") &&
    (nextQuery.from ?? "") === queryParam("from") &&
    (nextQuery.to ?? "") === queryParam("to") &&
    (nextQuery.range ?? "") === queryParam("range") &&
    (nextQuery.sort ?? "") === queryParam("sort") &&
    (nextQuery.order ?? "") === queryParam("order");
  if (!same) {
    void router.replace({ query: nextQuery });
  }
});

useLiveRefresh({
  topics: ["runs", "dashboard"],
  refresh: async () => {
    await load();
  },
});
useLiveRefresh({
  topics: ["projects"],
  refresh: async () => {
    await loadProjects();
  },
});

void loadProjects();
</script>

<template>
  <div>
    <PageHeader
      title="Impact"
      subtitle="Individual impact items behind dashboard category totals"
    />

    <div v-if="error" class="alert alert-error">{{ error }}</div>

    <div class="filter-bar mb-7">
      <select
        id="impact-category"
        v-model="categoryFilter"
        class="select"
        aria-label="Category"
      >
        <option value="">All categories</option>
        <option
          v-for="option in categoryOptions"
          :key="option.value"
          :value="option.value"
        >
          {{ option.label }}
        </option>
      </select>
      <select
        id="impact-project"
        v-model="projectFilter"
        class="select"
        aria-label="Project"
      >
        <option value="">All projects</option>
        <option v-for="project in projects" :key="project.id" :value="project.id">
          {{ project.name }}
        </option>
      </select>
    </div>

    <div v-if="loading" class="empty">Loading impact items…</div>
    <div v-else-if="items.length === 0" class="empty">
      No impact items match this filter
    </div>
    <template v-else>
      <div class="table-wrap">
        <table class="data">
          <thead>
            <tr>
              <SortableTh
                column="category"
                label="Category"
                :sort="sort"
                :order="order"
                @sort="setSort"
              />
              <SortableTh
                column="subject"
                label="Subject"
                :sort="sort"
                :order="order"
                @sort="setSort"
              />
              <th>Summary</th>
              <th>Verification</th>
              <SortableTh
                column="projectName"
                label="Project"
                :sort="sort"
                :order="order"
                @sort="setSort"
              />
              <SortableTh
                column="agentName"
                label="Agent"
                :sort="sort"
                :order="order"
                @sort="setSort"
              />
              <SortableTh
                column="createdAt"
                label="Created"
                :sort="sort"
                :order="order"
                @sort="setSort"
              />
              <th>Run</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in items" :key="item.id">
              <td>
                <span class="inline-icon-label">
                  <UiIcon :icon="impactCategorySpec(item.category).icon" :size="14" />
                  {{ impactCategoryLabel(item.category) }}
                </span>
              </td>
              <td>{{ item.subject }}</td>
              <td class="muted">{{ item.summary }}</td>
              <td>
                <VerificationBadge :verification="item.verification" />
              </td>
              <td>{{ item.projectName }}</td>
              <td>{{ item.agentName }}</td>
              <td>{{ formatWhen(item.createdAt) }}</td>
              <td>
                <RouterLink :to="{ name: 'run-detail', params: { id: item.runId } }">
                  Open run
                </RouterLink>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <TablePager
        v-model:page="page"
        :page-count="pages"
        :range-label="rangeLabel"
        :total="total"
      />
    </template>
  </div>
</template>

// web/src/contexts/catalog/views/ImpactView.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { AppSelect as Select } from "@/ui/AppSelect";

import { listImpactItems, listProjects, useCatalogStore } from "@/contexts/catalog/contract";
import { PageHeader } from "@/ui/PageHeader";
import { SortableTh } from "@/ui/SortableTh";
import { TablePager } from "@/ui/TablePager";
import { UiIcon } from "@/ui/UiIcon";
import { VerificationBadge } from "@/ui/status/VerificationBadge";
import { useBindStoreRefresh } from "@/platform/bind-store-refresh";
import { useServerTable } from "@/platform/useServerTable";
import { MAX_PAGE_LIMIT } from "@/kernel/pagination";
import {
  IMPACT_CATEGORIES,
  impactCategoryLabel,
  impactCategorySpec,
} from "@/kernel/stat-metrics";
import type { Order } from "@/platform/useClientPager";
import type { Project } from "@/contexts/catalog/types";

const IMPACT_SORT_ALLOWED = [
  "createdAt",
  "category",
  "subject",
  "projectName",
  "agentName",
] as const;

function formatWhen(value: string): string {
  try {
    return new Date(value).toLocaleString();
  } catch {
    return value;
  }
}

export function ImpactView() {
  const [searchParams, setSearchParams] = useSearchParams();

  const initialSort = useMemo(() => {
    const v = searchParams.get("sort") ?? "";
    return (IMPACT_SORT_ALLOWED as readonly string[]).includes(v) ? v : "createdAt";
  }, [searchParams]);
  const initialOrder: Order = searchParams.get("order") === "asc" ? "asc" : "desc";

  const [projects, setProjects] = useState<Project[]>([]);
  const [categoryFilter, setCategoryFilter] = useState(searchParams.get("category") ?? "");
  const [projectFilter, setProjectFilter] = useState(searchParams.get("projectId") ?? "");
  const [fromFilter, setFromFilter] = useState(searchParams.get("from") ?? "");
  const [toFilter, setToFilter] = useState(searchParams.get("to") ?? "");
  const [rangeFilter, setRangeFilter] = useState(searchParams.get("range") ?? "");

  const table = useServerTable({
    defaultSort: initialSort,
    defaultOrder: initialOrder,
    watchSources: [categoryFilter, projectFilter, fromFilter, toFilter],
    fetchPage: ({ limit, offset, sort, order }) =>
      listImpactItems({
        limit,
        offset,
        sort,
        order,
        category: categoryFilter || undefined,
        projectId: projectFilter || undefined,
        from: fromFilter || undefined,
        to: toFilter || undefined,
      }),
  });

  const loadProjects = useCallback(async () => {
    const result = await listProjects({ limit: MAX_PAGE_LIMIT, offset: 0 });
    setProjects(result.items);
  }, []);

  useEffect(() => {
    void loadProjects();
  }, [loadProjects]);

  useBindStoreRefresh(useCatalogStore.getState(), table.load);
  useBindStoreRefresh(useCatalogStore.getState(), loadProjects);

  useEffect(() => {
    const next = new URLSearchParams(searchParams);
    if (categoryFilter) next.set("category", categoryFilter);
    else next.delete("category");
    if (projectFilter) next.set("projectId", projectFilter);
    else next.delete("projectId");
    if (fromFilter) next.set("from", fromFilter);
    else next.delete("from");
    if (toFilter) next.set("to", toFilter);
    else next.delete("to");
    if (rangeFilter) next.set("range", rangeFilter);
    else next.delete("range");
    if (table.sort !== "createdAt" || table.order !== "desc") {
      next.set("sort", table.sort);
      next.set("order", table.order);
    } else {
      next.delete("sort");
      next.delete("order");
    }
    if (next.toString() !== searchParams.toString()) {
      setSearchParams(next, { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [categoryFilter, projectFilter, fromFilter, toFilter, rangeFilter, table.sort, table.order]);

  const categoryOptions = [
    { value: "", label: "All categories" },
    ...IMPACT_CATEGORIES.map((c) => ({ value: c, label: impactCategoryLabel(c) })),
  ];
  const projectOptions = [
    { value: "", label: "All projects" },
    ...projects.map((p) => ({ value: p.id, label: p.name })),
  ];

  return (
    <div>
      <PageHeader
        title="Impact"
        subtitle="Individual impact items behind dashboard category totals"
      />

      {table.error ? <div className="alert alert-error">{table.error}</div> : null}

      <div className="filter-bar mb-7">
        <div style={{ minWidth: 200 }}>
          <Select
            inputId="impact-category"
            aria-label="Category"
            value={categoryOptions.find((o) => o.value === categoryFilter) ?? categoryOptions[0]}
            options={categoryOptions}
            onChange={(opt) => setCategoryFilter(opt?.value ?? "")}
            isSearchable={false}
          />
        </div>
        <div style={{ minWidth: 200 }}>
          <Select
            inputId="impact-project"
            aria-label="Project"
            value={projectOptions.find((o) => o.value === projectFilter) ?? projectOptions[0]}
            options={projectOptions}
            onChange={(opt) => setProjectFilter(opt?.value ?? "")}
            isSearchable={false}
          />
        </div>
        {/* keep from/to and range URL round-trip capability */}
        {fromFilter || toFilter || rangeFilter ? (
          <span className="muted text-sm">
            {fromFilter ? <>from {fromFilter} </> : null}
            {toFilter ? <>to {toFilter} </> : null}
            {rangeFilter ? <>· {rangeFilter}</> : null}
          </span>
        ) : null}
        <button
          type="button"
          style={{ display: "none" }}
          onClick={() => {
            setFromFilter("");
            setToFilter("");
            setRangeFilter("");
          }}
        />
      </div>

      {table.loading ? (
        <div className="empty">Loading impact items…</div>
      ) : table.items.length === 0 ? (
        <div className="empty">No impact items match this filter</div>
      ) : (
        <>
          <div className="table-wrap">
            <table className="data">
              <thead>
                <tr>
                  <SortableTh
                    column="category"
                    label="Category"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <SortableTh
                    column="subject"
                    label="Subject"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <th>Summary</th>
                  <th>Verification</th>
                  <SortableTh
                    column="projectName"
                    label="Project"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <SortableTh
                    column="agentName"
                    label="Agent"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <SortableTh
                    column="createdAt"
                    label="Created"
                    sort={table.sort}
                    order={table.order}
                    onSort={table.setSort}
                  />
                  <th>Run</th>
                </tr>
              </thead>
              <tbody>
                {table.items.map((item) => (
                  <tr key={item.id}>
                    <td>
                      <span className="inline-icon-label">
                        <UiIcon icon={impactCategorySpec(item.category).icon} size={14} />
                        {impactCategoryLabel(item.category)}
                      </span>
                    </td>
                    <td>{item.subject}</td>
                    <td className="muted">{item.summary}</td>
                    <td>
                      <VerificationBadge verification={item.verification} />
                    </td>
                    <td>{item.projectName}</td>
                    <td>{item.agentName}</td>
                    <td>{formatWhen(item.createdAt)}</td>
                    <td>
                      <Link to={`/runs/${item.runId}`}>Open run</Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <TablePager
            page={table.page}
            pageCount={table.pages}
            rangeLabel={table.rangeLabel}
            total={table.total}
            onPageChange={table.setPage}
            loading={table.loading}
          />
        </>
      )}
    </div>
  );
}
