// web/src/contexts/catalog/views/ProjectConfigurationView.tsx
import { ProjectConfigurationPanel } from "@/contexts/catalog/components/ProjectConfigurationPanel";
import { useProjectShell } from "@/contexts/catalog/project-shell";

export function ProjectConfigurationView() {
  const { project, projectAgents, lastSync } = useProjectShell();
  if (!project) return null;
  return (
    <ProjectConfigurationPanel project={project} agents={projectAgents} lastSync={lastSync} />
  );
}

// web/src/contexts/catalog/views/ProjectConfigurationView.vue
<script setup lang="ts">
import { inject } from "vue";

import ProjectConfigurationPanel from "@/contexts/catalog/components/ProjectConfigurationPanel.vue";
import { projectShellKey } from "@/contexts/catalog/project-shell";

const shell = inject(projectShellKey);
if (!shell) {
  throw new Error("ProjectConfigurationView requires ProjectShellView");
}

const { project, projectAgents, lastSync } = shell;
</script>

<template>
  <ProjectConfigurationPanel
    v-if="project"
    :project="project"
    :agents="projectAgents"
    :last-sync="lastSync"
  />
</template>
