// web/src/contexts/catalog/views/ProjectHealthView.vue
<script setup lang="ts">
import { inject } from "vue";

import ProjectHealthPanel from "@/contexts/catalog/components/ProjectHealthPanel.vue";
import { projectShellKey } from "@/contexts/catalog/project-shell";

const shell = inject(projectShellKey);
if (!shell) {
  throw new Error("ProjectHealthView requires ProjectShellView");
}

const { project, doctor } = shell;
</script>

<template>
  <ProjectHealthPanel v-if="project" :project="project" :doctor="doctor" />
</template>

// web/src/contexts/catalog/views/ProjectHealthView.tsx
import { ProjectHealthPanel } from "@/contexts/catalog/components/ProjectHealthPanel";
import { useProjectShell } from "@/contexts/catalog/project-shell";

export function ProjectHealthView() {
  const { project, doctor } = useProjectShell();
  if (!project) return null;
  return <ProjectHealthPanel project={project} doctor={doctor} />;
}
