// web/src/ui/status/DeliveryBadge.tsx
import type { WorkDelivery } from "@gojo/contracts/types";

import { StatusBadge } from "@/ui/StatusBadge";
import { deliveryStatus } from "@/kernel/status-icons";

export function DeliveryBadge({ delivery }: { delivery: WorkDelivery | string }) {
  const spec = deliveryStatus(delivery);
  return <StatusBadge tone={spec.tone} label={spec.label} />;
}

// web/src/components/status/DeliveryBadge.vue
<script setup lang="ts">
import { computed } from "vue";

import StatusBadge from "@/components/StatusBadge.vue";
import { deliveryStatus } from "@/lib/status-icons";
import type { WorkDelivery } from "@/types";

const props = withDefaults(
  defineProps<{
    delivery: WorkDelivery | string;
    showLabel?: boolean;
  }>(),
  { showLabel: false },
);

const spec = computed(() => deliveryStatus(props.delivery));
</script>

<template>
  <StatusBadge
    :icon="spec.icon"
    :tone="spec.tone"
    :label="spec.label"
    :show-label="showLabel"
  />
</template>
