// web/src/ui/status/SyncStateBadge.tsx
import type { SourceSyncState } from "@gojo/contracts/types";

import { StatusBadge } from "@/ui/StatusBadge";
import { syncStateStatus } from "@/kernel/status-icons";

export function SyncStateBadge({
  syncState,
  showLabel: _showLabel = true,
}: {
  syncState: SourceSyncState | string;
  showLabel?: boolean;
}) {
  const spec = syncStateStatus(syncState);
  return <StatusBadge tone={spec.tone} label={spec.label} />;
}

// web/src/components/status/SyncStateBadge.vue
<script setup lang="ts">
import { computed } from "vue";

import StatusBadge from "@/components/StatusBadge.vue";
import { syncStateStatus } from "@/lib/status-icons";
import type { SourceSyncState } from "@/types";

const props = withDefaults(
  defineProps<{
    syncState: SourceSyncState | string;
    showLabel?: boolean;
  }>(),
  { showLabel: true },
);

const spec = computed(() => syncStateStatus(props.syncState));
</script>

<template>
  <StatusBadge
    :icon="spec.icon"
    :tone="spec.tone"
    :label="spec.label"
    :show-label="showLabel"
  />
</template>
