// web/src/components/status/ExecutionBadge.vue
<script setup lang="ts">
import { computed } from "vue";

import StatusBadge from "@/components/StatusBadge.vue";
import { executionStatus } from "@/lib/status-icons";
import type { WorkExecution } from "@/types";

const props = withDefaults(
  defineProps<{
    execution: WorkExecution | string;
    showLabel?: boolean;
  }>(),
  { showLabel: false },
);

const spec = computed(() => executionStatus(props.execution));
</script>

<template>
  <StatusBadge
    :icon="spec.icon"
    :tone="spec.tone"
    :label="spec.label"
    :show-label="showLabel"
  />
</template>

// web/src/ui/status/ExecutionBadge.tsx
import type { WorkExecution } from "@gojo/contracts/types";

import { StatusBadge } from "@/ui/StatusBadge";
import { executionStatus } from "@/kernel/status-icons";

export function ExecutionBadge({
  execution,
  showLabel: _showLabel,
}: {
  execution: WorkExecution | string;
  showLabel?: boolean;
}) {
  const spec = executionStatus(execution);
  return <StatusBadge tone={spec.tone} label={spec.label} />;
}
