// web/src/ui/status/HealthBadge.tsx
import { StatusBadge } from "@/ui/StatusBadge";
import { healthStatus } from "@/kernel/status-icons";

export function HealthBadge({
  level,
  label,
}: {
  level: "ok" | "warn" | "error" | "missing" | string;
  label?: string;
}) {
  const spec = healthStatus(level);
  return <StatusBadge tone={spec.tone} label={label ?? spec.label} />;
}

// web/src/ui/status/HealthBadge.vue
<script setup lang="ts">
import { computed } from "vue";

import StatusBadge from "@/ui/StatusBadge.vue";
import { healthStatus } from "@/kernel/status-icons";

const props = withDefaults(
  defineProps<{
    level: "ok" | "warn" | "error" | "missing" | string;
    label?: string;
    showLabel?: boolean;
  }>(),
  { showLabel: true },
);

const spec = computed(() => healthStatus(props.level));
</script>

<template>
  <StatusBadge
    :icon="spec.icon"
    :tone="spec.tone"
    :label="label ?? spec.label"
    :show-label="showLabel"
  />
</template>
