// web/src/components/status/WorkResultBadge.vue
<script setup lang="ts">
import { computed } from "vue";

import StatusBadge from "@/components/StatusBadge.vue";
import { workResultStatus } from "@/lib/status-icons";
import type { WorkItem } from "@/types";

const props = withDefaults(
  defineProps<{
    item: Pick<WorkItem, "resolution" | "delivery" | "outcome">;
    showLabel?: boolean;
  }>(),
  { showLabel: false },
);

const spec = computed(() => workResultStatus(props.item));
</script>

<template>
  <StatusBadge
    :icon="spec.icon"
    :tone="spec.tone"
    :label="spec.label"
    :show-label="showLabel"
  />
</template>

// web/src/ui/status/WorkResultBadge.tsx
import { StatusBadge } from "@/ui/StatusBadge";
import { workResultStatus } from "@/kernel/status-icons";
import type { WorkItem } from "@/contexts/work/types";

export function WorkResultBadge({
  item,
}: {
  item: Pick<WorkItem, "resolution" | "delivery" | "outcome">;
}) {
  const spec = workResultStatus(item);
  return <StatusBadge tone={spec.tone} label={spec.label} />;
}
