// web/src/contexts/catalog/components/ProjectConfigurationPanel.vue
<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";

import type { Agent, Project, ProjectSyncResult } from "@/contexts/catalog/types";
import { parseManifestView } from "@/kernel/project-manifest";

const props = defineProps<{
  project: Project;
  agents: Agent[];
  lastSync: ProjectSyncResult | null;
}>();

const manifest = computed(() => parseManifestView(props.project.manifestJson));

const agentsByName = computed(() => {
  const map = new Map<string, Agent>();
  for (const agent of props.agents) {
    map.set(agent.name, agent);
  }
  return map;
});
</script>

<template>
  <section class="panel mb-7">
    <div class="panel-header">Sync</div>
    <div class="panel-body">
      <p class="muted">
        Sync reads <span class="mono">gojo.yaml</span> (or
        <span class="mono">.gojo/project.yaml</span>) and upserts profiles, agents, and
        schedules by name. Entries removed from the manifest are soft-disabled so they stop
        firing. Sync does not change git history or your working tree. Use
        <strong>Sync</strong> in the page header to run it.
      </p>
      <div v-if="lastSync" class="mt-5 project-sync-result">
        <div>
          Manifest:
          <span class="mono">{{ lastSync.manifestPath ?? "not found" }}</span>
        </div>
        <div class="muted mt-2">
          {{ lastSync.profiles }} profiles · {{ lastSync.agents }} agents ·
          {{ lastSync.schedules }} schedules
        </div>
      </div>
    </div>
  </section>

  <section class="panel mb-7">
    <div class="panel-header">Configuration</div>
    <div class="panel-body">
      <div v-if="!project.hasManifest" class="muted">
        No synced manifest yet. Run Sync after adding a
        <span class="mono">gojo.yaml</span>.
      </div>
      <template v-else-if="!manifest.ok">
        <div class="alert alert-error">Could not parse manifest: {{ manifest.error }}</div>
      </template>
      <template v-else>
        <div v-if="Object.keys(manifest.repository).length" class="mb-7">
          <div class="panel-subheader">Repository</div>
          <ul class="project-kv">
            <li v-for="(value, key) in manifest.repository" :key="key">
              <span class="mono">{{ key }}</span>
              <span class="muted">{{ String(value) }}</span>
            </li>
          </ul>
        </div>

        <div class="mb-7">
          <div class="panel-subheader">Profiles ({{ manifest.profiles.length }})</div>
          <div v-if="manifest.profiles.length === 0" class="muted">None</div>
          <div v-else class="table-wrap">
            <table class="data">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Adapter</th>
                  <th>Model</th>
                  <th>Timeout</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="profile in manifest.profiles" :key="profile.name">
                  <td class="entity-name">{{ profile.name }}</td>
                  <td class="mono">{{ profile.adapter }}</td>
                  <td class="mono muted">{{ profile.model ?? "—" }}</td>
                  <td class="mono muted">{{ profile.timeout ?? "—" }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="mb-7">
          <div class="panel-subheader">Agents ({{ manifest.agents.length }})</div>
          <div v-if="manifest.agents.length === 0" class="muted">None</div>
          <div v-else class="table-wrap">
            <table class="data">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Profile</th>
                  <th>Integration</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="agent in manifest.agents" :key="agent.name">
                  <td>
                    <RouterLink
                      v-if="agentsByName.get(agent.name)"
                      :to="{
                        name: 'agent-detail',
                        params: { id: agentsByName.get(agent.name)!.id },
                      }"
                      class="entity-name"
                    >
                      {{ agent.name }}
                    </RouterLink>
                    <span v-else class="entity-name">{{ agent.name }}</span>
                  </td>
                  <td class="mono">{{ agent.profile }}</td>
                  <td class="mono">{{ agent.integrationMode }}</td>
                  <td class="muted">{{ agent.description || "—" }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="mb-7">
          <div class="panel-subheader">Schedules ({{ manifest.schedules.length }})</div>
          <div v-if="manifest.schedules.length === 0" class="muted">None</div>
          <div v-else class="table-wrap">
            <table class="data">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Agent</th>
                  <th>Cron</th>
                  <th>Timezone</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="schedule in manifest.schedules" :key="schedule.name">
                  <td class="entity-name">{{ schedule.name }}</td>
                  <td class="mono">{{ schedule.agent }}</td>
                  <td class="mono">{{ schedule.cron }}</td>
                  <td class="mono muted">{{ schedule.timezone }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="mb-7">
          <div class="panel-subheader">
            Validation profiles ({{ manifest.validationProfiles.length }})
          </div>
          <div v-if="manifest.validationProfiles.length === 0" class="muted">None</div>
          <ul v-else class="project-kv">
            <li v-for="profile in manifest.validationProfiles" :key="profile.name">
              <span class="mono">{{ profile.name }}</span>
              <span class="muted">{{ profile.stepCount }} steps</span>
            </li>
          </ul>
        </div>

        <details class="project-raw-json">
          <summary class="muted">Advanced: raw JSON</summary>
          <pre class="pre-block">{{ manifest.prettyJson }}</pre>
        </details>
      </template>
    </div>
  </section>
</template>

// web/src/contexts/catalog/components/ProjectConfigurationPanel.tsx
import { useMemo } from "react";
import { Link } from "react-router-dom";

import type { Agent, Project, ProjectSyncResult } from "@/contexts/catalog/types";
import { parseManifestView } from "@/kernel/project-manifest";

export function ProjectConfigurationPanel({
  project,
  agents,
  lastSync,
}: {
  project: Project;
  agents: Agent[];
  lastSync: ProjectSyncResult | null;
}) {
  const manifest = useMemo(() => parseManifestView(project.manifestJson), [project.manifestJson]);
  const agentsByName = useMemo(() => {
    const map = new Map<string, Agent>();
    for (const agent of agents) map.set(agent.name, agent);
    return map;
  }, [agents]);

  return (
    <>
      <section className="panel mb-7">
        <div className="panel-header">Sync</div>
        <div className="panel-body">
          <p className="muted">
            Sync reads <span className="mono">gojo.yaml</span> (or{" "}
            <span className="mono">.gojo/project.yaml</span>) and upserts profiles, agents, and
            schedules by name. Entries removed from the manifest are soft-disabled so they stop
            firing. Sync does not change git history or your working tree. Use{" "}
            <strong>Sync</strong> in the page header to run it.
          </p>
          {lastSync ? (
            <div className="mt-5 project-sync-result">
              <div>
                Manifest: <span className="mono">{lastSync.manifestPath ?? "not found"}</span>
              </div>
              <div className="muted mt-2">
                {lastSync.profiles} profiles · {lastSync.agents} agents · {lastSync.schedules}{" "}
                schedules
              </div>
            </div>
          ) : null}
        </div>
      </section>

      <section className="panel mb-7">
        <div className="panel-header">Configuration</div>
        <div className="panel-body">
          {!project.hasManifest ? (
            <div className="muted">
              No synced manifest yet. Run Sync after adding a{" "}
              <span className="mono">gojo.yaml</span>.
            </div>
          ) : !manifest.ok ? (
            <div className="alert alert-error">Could not parse manifest: {manifest.error}</div>
          ) : (
            <>
              {Object.keys(manifest.repository).length ? (
                <div className="mb-7">
                  <div className="panel-subheader">Repository</div>
                  <ul className="project-kv">
                    {Object.entries(manifest.repository).map(([key, value]) => (
                      <li key={key}>
                        <span className="mono">{key}</span>
                        <span className="muted">{String(value)}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}

              <div className="mb-7">
                <div className="panel-subheader">Profiles ({manifest.profiles.length})</div>
                {manifest.profiles.length === 0 ? (
                  <div className="muted">None</div>
                ) : (
                  <div className="table-wrap">
                    <table className="data">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Adapter</th>
                          <th>Model</th>
                          <th>Timeout</th>
                        </tr>
                      </thead>
                      <tbody>
                        {manifest.profiles.map((profile) => (
                          <tr key={profile.name}>
                            <td className="entity-name">{profile.name}</td>
                            <td className="mono">{profile.adapter}</td>
                            <td className="mono muted">{profile.model ?? "—"}</td>
                            <td className="mono muted">{profile.timeout ?? "—"}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>

              <div className="mb-7">
                <div className="panel-subheader">Agents ({manifest.agents.length})</div>
                {manifest.agents.length === 0 ? (
                  <div className="muted">None</div>
                ) : (
                  <div className="table-wrap">
                    <table className="data">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Profile</th>
                          <th>Integration</th>
                          <th>Description</th>
                        </tr>
                      </thead>
                      <tbody>
                        {manifest.agents.map((agent) => {
                          const linked = agentsByName.get(agent.name);
                          return (
                            <tr key={agent.name}>
                              <td>
                                {linked ? (
                                  <Link to={`/agents/${linked.id}`} className="entity-name">
                                    {agent.name}
                                  </Link>
                                ) : (
                                  <span className="entity-name">{agent.name}</span>
                                )}
                              </td>
                              <td className="mono">{agent.profile}</td>
                              <td className="mono">{agent.integrationMode}</td>
                              <td className="muted">{agent.description || "—"}</td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>

              <div className="mb-7">
                <div className="panel-subheader">Schedules ({manifest.schedules.length})</div>
                {manifest.schedules.length === 0 ? (
                  <div className="muted">None</div>
                ) : (
                  <div className="table-wrap">
                    <table className="data">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Agent</th>
                          <th>Cron</th>
                          <th>Timezone</th>
                        </tr>
                      </thead>
                      <tbody>
                        {manifest.schedules.map((schedule) => (
                          <tr key={schedule.name}>
                            <td className="entity-name">{schedule.name}</td>
                            <td className="mono">{schedule.agent}</td>
                            <td className="mono">{schedule.cron}</td>
                            <td className="mono muted">{schedule.timezone}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>

              <div className="mb-7">
                <div className="panel-subheader">
                  Validation profiles ({manifest.validationProfiles.length})
                </div>
                {manifest.validationProfiles.length === 0 ? (
                  <div className="muted">None</div>
                ) : (
                  <ul className="project-kv">
                    {manifest.validationProfiles.map((profile) => (
                      <li key={profile.name}>
                        <span className="mono">{profile.name}</span>
                        <span className="muted">{profile.stepCount} steps</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              <details className="project-raw-json">
                <summary className="muted">Advanced: raw JSON</summary>
                <pre className="pre-block">{manifest.prettyJson}</pre>
              </details>
            </>
          )}
        </div>
      </section>
    </>
  );
}
