// web/src/contexts/catalog/components/ProjectImpactSection.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AppSelect as Select } from "@/ui/AppSelect";
import { ArrowRight } from "lucide-react";

import {
  getDashboardImpact,
  useOperationsStore,
} from "@/contexts/operations/contract";
import type { DashboardImpact } from "@/contexts/operations/contract";
import { useBindStoreRefresh } from "@/platform/bind-store-refresh";
import { AppButton } from "@/ui/AppButton";
import { StatGrid } from "@/ui/StatGrid";
import { StatTile } from "@/ui/StatTile";
import { VerificationBadge } from "@/ui/status/VerificationBadge";
import { compareLabel } from "@/kernel/stat-metrics";

type ImpactRange = "30d" | "90d" | "all";

const RANGE_OPTIONS: Array<{ value: ImpactRange; label: string }> = [
  { value: "30d", label: "Last 30 days" },
  { value: "90d", label: "Last 90 days" },
  { value: "all", label: "Lifetime" },
];

export type ProjectImpactSectionProps = {
  projectId: string;
  openPrTotal: number;
  mode?: "compact" | "full";
};

export function ProjectImpactSection({
  projectId,
  openPrTotal,
  mode = "full",
}: ProjectImpactSectionProps) {
  const [impact, setImpact] = useState<DashboardImpact | null>(null);
  const [impactRange, setImpactRange] = useState<ImpactRange>("30d");
  const [hiddenAgentIds, setHiddenAgentIds] = useState<Set<string>>(new Set());

  function impactWindowQs(base: Record<string, string> = {}): string {
    const s = new URLSearchParams(base);
    if (projectId) s.set("projectId", projectId);
    if (impact?.window.from) s.set("from", impact.window.from);
    if (impact?.window.to) s.set("to", impact.window.to);
    if (impactRange !== "all") s.set("range", impactRange);
    const str = s.toString();
    return str ? `?${str}` : "";
  }

  const mergedRoute = `/integrations${impactWindowQs({ status: "merged" })}`;
  const commitsRoute = `/integrations${impactWindowQs({ status: "committed" })}`;
  const succeededRunsRoute = `/runs${impactWindowQs({ state: "Succeeded" })}`;
  const deliveryRoute = `/projects/${projectId}/overview#attention`;
  const projectImpactRoute = `/projects/${projectId}/impact`;
  const browseAllRoute = `/impact${impactWindowQs()}`;

  const categoryRoute = (category: string) => `/impact${impactWindowQs({ category })}`;

  const impactAgents = useMemo(() => {
    const items = impact?.recentItems ?? [];
    const byId = new Map<string, string>();
    for (const item of items) {
      if (!byId.has(item.agentId)) byId.set(item.agentId, item.agentName);
    }
    return [...byId.entries()]
      .map(([id, name]) => ({ id, name }))
      .sort((a, b) => a.name.localeCompare(b.name));
  }, [impact]);

  const visibleImpactItems = useMemo(() => {
    const items = impact?.recentItems ?? [];
    if (hiddenAgentIds.size === 0) return items;
    return items.filter((item) => !hiddenAgentIds.has(item.agentId));
  }, [impact, hiddenAgentIds]);

  function isAgentVisible(agentId: string): boolean {
    return !hiddenAgentIds.has(agentId);
  }

  function toggleAgentVisibility(agentId: string) {
    setHiddenAgentIds((prev) => {
      const next = new Set(prev);
      if (next.has(agentId)) next.delete(agentId);
      else next.add(agentId);
      return next;
    });
  }

  const loadImpact = useCallback(async () => {
    try {
      const next = await getDashboardImpact({ projectId, range: impactRange });
      setImpact(next);
      setHiddenAgentIds((prev) => {
        const known = new Set(
          (next.recentItems ?? []).map((item) => item.agentId),
        );
        const filtered = new Set([...prev].filter((id) => known.has(id)));
        return filtered.size === prev.size ? prev : filtered;
      });
    } catch {
      setImpact(null);
    }
  }, [projectId, impactRange]);

  useEffect(() => {
    setImpact(null);
    setHiddenAgentIds(new Set());
    void loadImpact();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId, impactRange]);

  useBindStoreRefresh(useOperationsStore.getState(), loadImpact);

  if (!impact) return null;

  const rangeValue = RANGE_OPTIONS.find((o) => o.value === impactRange) ?? RANGE_OPTIONS[0];
  const impactCompareLbl = compareLabel("previousWindow", impact.range);

  return (
    <section className="panel mb-7">
      <div className="panel-header impact-header">
        <span>Impact</span>
        <div className="impact-header-actions">
          <div style={{ minWidth: 180 }}>
            <Select
              inputId={`project-impact-range-${mode}`}
              aria-label="Impact time range"
              value={rangeValue}
              options={RANGE_OPTIONS}
              onChange={(opt) => opt && setImpactRange(opt.value as ImpactRange)}
              isSearchable={false}
            />
          </div>
          {mode === "compact" ? (
            <AppButton size="sm" to={projectImpactRoute} iconBefore={<ArrowRight size={12} />}>
              See more
            </AppButton>
          ) : null}
        </div>
      </div>
      <div className="panel-body">
        <StatGrid>
          <StatTile
            metricKey="impact.mergedRuns"
            value={impact.totals.mergedRuns}
            previous={impact.previousTotals?.mergedRuns}
            compareLabel={impactCompareLbl}
            to={mergedRoute}
          />
          <StatTile
            metricKey="impact.prsOpen"
            value={openPrTotal}
            previous={impact.previousTotals?.prsOpen}
            compareLabel={impactCompareLbl}
            to={openPrTotal > 0 ? deliveryRoute : undefined}
          />
          <StatTile
            metricKey="impact.mergeRate"
            value={impact.totals.mergeRate}
            previous={impact.previousTotals?.mergeRate}
            compareLabel={impactCompareLbl}
          />
          <StatTile
            metricKey="impact.succeededRuns"
            value={impact.totals.succeededRuns}
            previous={impact.previousTotals?.succeededRuns}
            compareLabel={impactCompareLbl}
            to={succeededRunsRoute}
          />
          <StatTile
            metricKey="impact.commits"
            value={impact.totals.commits}
            previous={impact.previousTotals?.commits}
            compareLabel={impactCompareLbl}
            to={commitsRoute}
          />
        </StatGrid>

        {mode === "full" ? (
          <>
            {impact.categoryTotals.length ? (
              <div className="mt-5">
                <div className="panel-subheader">By category</div>
                <div className="category-chips">
                  {impact.categoryTotals.map((row) => (
                    <Link
                      key={row.category}
                      to={categoryRoute(row.category)}
                      className="category-chip"
                    >
                      {row.category}
                      <span className="category-chip__count">{row.runs}</span>
                    </Link>
                  ))}
                </div>
              </div>
            ) : null}
            {impactAgents.length ? (
              <div className="mt-5">
                <div className="panel-subheader">Agents in range</div>
                <div className="agent-visibility">
                  {impactAgents.map((agent) => (
                    <button
                      key={agent.id}
                      type="button"
                      className={`agent-visibility__chip${!isAgentVisible(agent.id) ? " agent-visibility__chip--hidden" : ""}`}
                      onClick={() => toggleAgentVisibility(agent.id)}
                    >
                      {agent.name}
                    </button>
                  ))}
                </div>
              </div>
            ) : null}
            {visibleImpactItems.length ? (
              <div className="table-wrap mt-5">
                <table className="data">
                  <thead>
                    <tr>
                      <th>Agent</th>
                      <th>Subject</th>
                      <th>Summary</th>
                      <th>Trust</th>
                    </tr>
                  </thead>
                  <tbody>
                    {visibleImpactItems.map((item) => (
                      <tr key={item.id}>
                        <td>
                          <Link to={`/runs/${item.runId}`} className="entity-name">
                            {item.agentName}
                          </Link>
                        </td>
                        <td className="mono">{item.subject}</td>
                        <td>{item.summary}</td>
                        <td>
                          <VerificationBadge verification={item.verification} />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : impact.recentItems.length > 0 ? (
              <div className="muted text-sm impact-empty">
                All agents are hidden — turn an agent back on to see its impact items
              </div>
            ) : null}
            <div className="toolbar mt-5">
              <AppButton size="sm" to={browseAllRoute} iconBefore={<ArrowRight size={12} />}>
                Browse all impact items
              </AppButton>
            </div>
          </>
        ) : null}
      </div>
    </section>
  );
}

// web/src/contexts/catalog/components/ProjectImpactSection.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { RouterLink } from "vue-router";
import { ArrowRight } from "lucide-vue-next";

import { getDashboardImpact } from "@/contexts/operations/contract";
import { bindStoreRefresh } from "@/platform/bind-store-refresh";
import { useOperationsStore } from "@/contexts/operations/contract";
import AppButton from "@/ui/AppButton.vue";
import StatGrid from "@/ui/StatGrid.vue";
import StatTile from "@/ui/StatTile.vue";
import VerificationBadge from "@/ui/status/VerificationBadge.vue";
import { compareLabel } from "@/kernel/stat-metrics";
import type { DashboardImpact } from "@/contexts/operations/contract";

const props = withDefaults(
  defineProps<{
    projectId: string;
    openPrTotal: number;
    /** compact = stats + See more; full = categories, agents, recent items */
    mode?: "compact" | "full";
  }>(),
  { mode: "full" },
);

type ImpactRange = "30d" | "90d" | "all";

const impact = ref<DashboardImpact | null>(null);
const impactRange = ref<ImpactRange>("30d");
const hiddenAgentIds = ref<Set<string>>(new Set());

const operationsStore = useOperationsStore();

function impactCompareLabel(): string {
  return compareLabel("previousWindow", impact.value?.range);
}

function impactWindowQuery(base: Record<string, string> = {}): Record<string, string> {
  const query: Record<string, string> = {
    ...base,
    projectId: props.projectId,
  };
  const from = impact.value?.window.from;
  const to = impact.value?.window.to;
  if (from) query.from = from;
  if (to) query.to = to;
  if (impactRange.value !== "all") {
    query.range = impactRange.value;
  }
  return query;
}

const mergedRoute = computed(() => ({
  name: "integrations" as const,
  query: impactWindowQuery({ status: "merged" }),
}));
const commitsRoute = computed(() => ({
  name: "integrations" as const,
  query: impactWindowQuery({ status: "committed" }),
}));
const succeededRunsRoute = computed(() => ({
  name: "runs" as const,
  query: impactWindowQuery({ state: "Succeeded" }),
}));
const deliveryRoute = computed(() => ({
  name: "project-overview" as const,
  params: { id: props.projectId },
  hash: "#attention",
}));
const projectImpactRoute = computed(() => ({
  name: "project-impact" as const,
  params: { id: props.projectId },
}));
const browseAllRoute = computed(() => ({
  name: "impact" as const,
  query: impactWindowQuery(),
}));

function categoryRoute(category: string) {
  return {
    name: "impact" as const,
    query: impactWindowQuery({ category }),
  };
}

const impactAgents = computed(() => {
  const items = impact.value?.recentItems ?? [];
  const byId = new Map<string, string>();
  for (const item of items) {
    if (!byId.has(item.agentId)) {
      byId.set(item.agentId, item.agentName);
    }
  }
  return [...byId.entries()]
    .map(([id, name]) => ({ id, name }))
    .sort((a, b) => a.name.localeCompare(b.name));
});

const visibleImpactItems = computed(() => {
  const items = impact.value?.recentItems ?? [];
  if (hiddenAgentIds.value.size === 0) {
    return items;
  }
  return items.filter((item) => !hiddenAgentIds.value.has(item.agentId));
});

function isAgentVisible(agentId: string): boolean {
  return !hiddenAgentIds.value.has(agentId);
}

function toggleAgentVisibility(agentId: string) {
  const next = new Set(hiddenAgentIds.value);
  if (next.has(agentId)) {
    next.delete(agentId);
  } else {
    next.add(agentId);
  }
  hiddenAgentIds.value = next;
}

async function loadImpact() {
  try {
    impact.value = await getDashboardImpact({
      projectId: props.projectId,
      range: impactRange.value,
    });
    const known = new Set(impactAgents.value.map((agent) => agent.id));
    const next = new Set([...hiddenAgentIds.value].filter((id) => known.has(id)));
    if (next.size !== hiddenAgentIds.value.size) {
      hiddenAgentIds.value = next;
    }
  } catch {
    impact.value = null;
  }
}

watch(() => props.projectId, () => {
  impact.value = null;
  hiddenAgentIds.value = new Set();
  void loadImpact();
});

watch(impactRange, () => {
  void loadImpact();
});

bindStoreRefresh(operationsStore, loadImpact);
</script>

<template>
  <section v-if="impact" class="panel mb-7">
    <div class="panel-header impact-header">
      <span>Impact</span>
      <div class="impact-header-actions">
        <select
          :id="`project-impact-range-${mode}`"
          v-model="impactRange"
          class="select"
          aria-label="Impact time range"
        >
          <option value="30d">Last 30 days</option>
          <option value="90d">Last 90 days</option>
          <option value="all">Lifetime</option>
        </select>
        <AppButton
          v-if="mode === 'compact'"
          size="sm"
          :icon="ArrowRight"
          :to="projectImpactRoute"
        >
          See more
        </AppButton>
      </div>
    </div>
    <div class="panel-body">
      <StatGrid>
        <StatTile
          metric-key="impact.mergedRuns"
          :value="impact.totals.mergedRuns"
          :previous="impact.previousTotals?.mergedRuns"
          :compare-label="impactCompareLabel()"
          :to="mergedRoute"
        />
        <StatTile
          metric-key="impact.prsOpen"
          :value="openPrTotal"
          :previous="impact.previousTotals?.prsOpen"
          :compare-label="impactCompareLabel()"
          :to="openPrTotal > 0 ? deliveryRoute : undefined"
        />
        <StatTile
          metric-key="impact.mergeRate"
          :value="impact.totals.mergeRate"
          :previous="impact.previousTotals?.mergeRate"
          :compare-label="impactCompareLabel()"
        />
        <StatTile
          metric-key="impact.succeededRuns"
          :value="impact.totals.succeededRuns"
          :previous="impact.previousTotals?.succeededRuns"
          :compare-label="impactCompareLabel()"
          :to="succeededRunsRoute"
        />
        <StatTile
          metric-key="impact.commits"
          :value="impact.totals.commits"
          :previous="impact.previousTotals?.commits"
          :compare-label="impactCompareLabel()"
          :to="commitsRoute"
        />
      </StatGrid>

      <template v-if="mode === 'full'">
        <div v-if="impact.categoryTotals.length" class="mt-5">
          <div class="panel-subheader">By category</div>
          <div class="category-chips">
            <RouterLink
              v-for="row in impact.categoryTotals"
              :key="row.category"
              :to="categoryRoute(row.category)"
              class="category-chip"
            >
              {{ row.category }}
              <span class="category-chip__count">{{ row.runs }}</span>
            </RouterLink>
          </div>
        </div>
        <div v-if="impactAgents.length" class="mt-5">
          <div class="panel-subheader">Agents in range</div>
          <div class="agent-visibility">
            <button
              v-for="agent in impactAgents"
              :key="agent.id"
              type="button"
              class="agent-visibility__chip"
              :class="{ 'agent-visibility__chip--hidden': !isAgentVisible(agent.id) }"
              @click="toggleAgentVisibility(agent.id)"
            >
              {{ agent.name }}
            </button>
          </div>
        </div>
        <div v-if="visibleImpactItems.length" class="table-wrap mt-5">
          <table class="data">
            <thead>
              <tr>
                <th>Agent</th>
                <th>Subject</th>
                <th>Summary</th>
                <th>Trust</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in visibleImpactItems" :key="item.id">
                <td>
                  <RouterLink
                    :to="{ name: 'run-detail', params: { id: item.runId } }"
                    class="entity-name"
                  >
                    {{ item.agentName }}
                  </RouterLink>
                </td>
                <td class="mono">{{ item.subject }}</td>
                <td>{{ item.summary }}</td>
                <td>
                  <VerificationBadge :verification="item.verification" />
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div
          v-else-if="impact.recentItems.length > 0"
          class="muted text-sm impact-empty"
        >
          All agents are hidden — turn an agent back on to see its impact items
        </div>
        <div class="toolbar mt-5">
          <AppButton size="sm" :icon="ArrowRight" :to="browseAllRoute">
            Browse all impact items
          </AppButton>
        </div>
      </template>
    </div>
  </section>
</template>

<style scoped>
.impact-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.75rem;
}

.impact-header-actions {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}
</style>
