// web/src/contexts/catalog/components/ProjectHealthPanel.vue
<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";

import type { Project } from "@/contexts/catalog/types";
import type { ProjectDoctorResult } from "@/contexts/operations/contract";
import {
  computeProjectHealth,
  projectHealthFactors,
} from "@/kernel/project-manifest";
import HealthBadge from "@/ui/status/HealthBadge.vue";

const props = defineProps<{
  project: Project;
  doctor: ProjectDoctorResult | null;
}>();

const health = computed(() => computeProjectHealth(props.project, props.doctor));

const workspaceFiles = computed(() => props.doctor?.workspaceFiles ?? null);

const factors = computed(() =>
  projectHealthFactors(props.project, props.doctor, {
    workspaceFiles: workspaceFiles.value,
  }),
);

const scoredFactors = computed(() => factors.value.filter((factor) => factor.scored));
const infoFactors = computed(() => factors.value.filter((factor) => !factor.scored));
</script>

<template>
  <section class="panel mb-7">
    <div class="panel-header">
      Health
      <HealthBadge :level="health.level" :label="health.label" />
    </div>
    <div class="panel-body">
      <p class="muted">
        Score is 0–100 from project doctor checks on the registered base checkout (not a
        percentage). Fix failing scored factors below, then refresh this page.
      </p>

      <div v-if="!doctor" class="muted mt-5">Doctor results unavailable.</div>
      <template v-else>
        <div class="mt-5">
          <div class="panel-subheader">Score factors</div>
          <ul class="health-checklist">
            <li v-for="factor in scoredFactors" :key="factor.id">
              <span :class="factor.ok ? 'ok' : 'bad'">●</span>
              {{ factor.label }}
              <span v-if="!factor.ok && factor.penalty > 0" class="muted">
                · −{{ factor.penalty }}
              </span>
              <p v-if="factor.remediation" class="muted text-sm mt-2">
                {{ factor.remediation }}
              </p>
              <ul
                v-if="factor.details?.length"
                class="muted mt-2 health-dirty-files"
              >
                <li
                  v-for="detail in factor.details.slice(0, 12)"
                  :key="detail"
                  class="mono"
                >
                  {{ detail }}
                </li>
                <li v-if="factor.details.length > 12">
                  … +{{ factor.details.length - 12 }} more
                </li>
              </ul>
            </li>
          </ul>
        </div>

        <div v-if="infoFactors.length" class="mt-7">
          <div class="panel-subheader">Also checked (not in score)</div>
          <ul class="health-checklist">
            <li v-for="factor in infoFactors" :key="factor.id">
              <span :class="factor.ok ? 'ok' : 'bad'">●</span>
              {{ factor.label }}
              <p v-if="factor.remediation" class="muted text-sm mt-2">
                {{ factor.remediation }}
              </p>
              <ul
                v-if="factor.details?.length"
                class="muted mt-2 health-dirty-files"
              >
                <li
                  v-for="detail in factor.details"
                  :key="detail"
                  class="mono"
                >
                  {{ detail }}
                </li>
              </ul>
              <pre
                v-if="
                  factor.id === 'workspace-generated' &&
                  workspaceFiles?.suggestedGitignore
                "
                class="mono mt-2 gitignore-suggestion"
              >{{ workspaceFiles.suggestedGitignore }}</pre>
            </li>
          </ul>
        </div>

        <p class="muted text-sm mt-5">
          CLI:
          <span class="mono">gojo project doctor {{ project.id }}</span>
          ·
          <RouterLink
            :to="{ name: 'project-configuration', params: { id: project.id } }"
            class="entity-name"
          >
            Configuration
          </RouterLink>
          for sync and manifest.
        </p>
      </template>
    </div>
  </section>
</template>

// web/src/contexts/catalog/components/ProjectHealthPanel.tsx
import { useMemo } from "react";
import { Link } from "react-router-dom";

import type { Project } from "@/contexts/catalog/types";
import type { ProjectDoctorResult } from "@/contexts/operations/contract";
import {
  computeProjectHealth,
  projectHealthFactors,
} from "@/kernel/project-manifest";
import { HealthBadge } from "@/ui/status/HealthBadge";

export function ProjectHealthPanel({
  project,
  doctor,
}: {
  project: Project;
  doctor: ProjectDoctorResult | null;
}) {
  const health = useMemo(() => computeProjectHealth(project, doctor), [project, doctor]);
  const workspaceFiles = doctor?.workspaceFiles ?? null;
  const factors = useMemo(
    () => projectHealthFactors(project, doctor, { workspaceFiles }),
    [project, doctor, workspaceFiles],
  );
  const scored = factors.filter((f) => f.scored);
  const info = factors.filter((f) => !f.scored);

  return (
    <section className="panel mb-7">
      <div className="panel-header">
        Health
        <HealthBadge level={health.level} label={health.label} />
      </div>
      <div className="panel-body">
        <p className="muted">
          Score is 0–100 from project doctor checks on the registered base checkout (not a
          percentage). Fix failing scored factors below, then refresh this page.
        </p>
        {!doctor ? (
          <div className="muted mt-5">Doctor results unavailable.</div>
        ) : (
          <>
            <div className="mt-5">
              <div className="panel-subheader">Score factors</div>
              <ul className="health-checklist">
                {scored.map((factor) => (
                  <li key={factor.id}>
                    <span className={factor.ok ? "ok" : "bad"}>●</span> {factor.label}
                    {!factor.ok && factor.penalty > 0 ? (
                      <span className="muted"> · −{factor.penalty}</span>
                    ) : null}
                    {factor.remediation ? (
                      <p className="muted text-sm mt-2">{factor.remediation}</p>
                    ) : null}
                    {factor.details?.length ? (
                      <ul className="muted mt-2 health-dirty-files">
                        {factor.details.slice(0, 12).map((detail) => (
                          <li key={detail} className="mono">
                            {detail}
                          </li>
                        ))}
                        {factor.details.length > 12 ? (
                          <li>… +{factor.details.length - 12} more</li>
                        ) : null}
                      </ul>
                    ) : null}
                  </li>
                ))}
              </ul>
            </div>

            {info.length ? (
              <div className="mt-7">
                <div className="panel-subheader">Also checked (not in score)</div>
                <ul className="health-checklist">
                  {info.map((factor) => (
                    <li key={factor.id}>
                      <span className={factor.ok ? "ok" : "bad"}>●</span> {factor.label}
                      {factor.remediation ? (
                        <p className="muted text-sm mt-2">{factor.remediation}</p>
                      ) : null}
                      {factor.details?.length ? (
                        <ul className="muted mt-2 health-dirty-files">
                          {factor.details.map((detail) => (
                            <li key={detail} className="mono">
                              {detail}
                            </li>
                          ))}
                        </ul>
                      ) : null}
                      {factor.id === "workspace-generated" &&
                      workspaceFiles?.suggestedGitignore ? (
                        <pre className="mono mt-2 gitignore-suggestion">
                          {workspaceFiles.suggestedGitignore}
                        </pre>
                      ) : null}
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}

            <p className="muted text-sm mt-5">
              CLI: <span className="mono">gojo project doctor {project.id}</span> ·{" "}
              <Link to={`/projects/${project.id}/configuration`} className="entity-name">
                Configuration
              </Link>{" "}
              for sync and manifest.
            </p>
          </>
        )}
      </div>
    </section>
  );
}
