// web/src/contexts/work/components/ProjectSourcesPanel.vue
<script setup lang="ts">
import type { ProjectSource } from "@/contexts/work/types";
import SyncStateBadge from "@/ui/status/SyncStateBadge.vue";

defineProps<{
  sources: ProjectSource[];
}>();
</script>

<template>
  <div v-if="sources.length > 0" class="source-health mt-5">
    <span
      v-for="source in sources"
      :key="source.id"
      class="source-health__item"
      :title="source.lastError ?? `Observed ${source.observedAt ?? 'never'}`"
    >
      <span class="muted text-sm">{{ source.displayName }}</span>
      <SyncStateBadge :sync-state="source.syncState" :show-label="false" />
    </span>
  </div>
</template>

// web/src/contexts/work/components/ProjectSourcesPanel.tsx
import type { ProjectSource } from "@/contexts/work/types";
import { SyncStateBadge } from "@/ui/status/SyncStateBadge";

export function ProjectSourcesPanel({ sources }: { sources: ProjectSource[] }) {
  if (sources.length === 0) return null;
  return (
    <div className="source-health mt-5">
      {sources.map((source) => (
        <span
          key={source.id}
          className="source-health__item"
          title={source.lastError ?? `Observed ${source.observedAt ?? "never"}`}
        >
          <span className="muted text-sm">{source.displayName}</span>
          <SyncStateBadge syncState={source.syncState} showLabel={false} />
        </span>
      ))}
    </div>
  );
}
