// web/src/contexts/scheduling/components/SettingsSchedulingSection.vue
<script setup lang="ts">
import { ref } from "vue";

import {
  getSchedulingPolicy,
  updateSchedulingPolicy,
} from "@/contexts/scheduling/contract";
import AppButton from "@/ui/AppButton.vue";
import { Save } from "lucide-vue-next";
import type { SchedulingPolicy } from "@/contexts/scheduling/types";

const emit = defineEmits<{
  error: [message: string];
  message: [message: string];
}>();

const scheduling = ref<SchedulingPolicy>({
  maxConcurrentRuns: 2,
  maxConcurrentRunsPerProject: 1,
  minStartIntervalMs: 30_000,
  maxLoadPerCpu: 1,
});
const busy = ref(false);

async function load() {
  scheduling.value = await getSchedulingPolicy();
}

async function saveScheduling() {
  busy.value = true;
  try {
    scheduling.value = await updateSchedulingPolicy({
      maxConcurrentRuns: Number(scheduling.value.maxConcurrentRuns),
      maxConcurrentRunsPerProject: Number(scheduling.value.maxConcurrentRunsPerProject),
      minStartIntervalMs: Number(scheduling.value.minStartIntervalMs),
      maxLoadPerCpu: Number(scheduling.value.maxLoadPerCpu),
    });
    emit("message", "Scheduling policy saved");
  } catch (err) {
    emit("error", err instanceof Error ? err.message : "Failed to save scheduling policy");
  } finally {
    busy.value = false;
  }
}

defineExpose({ load });
void load();
</script>

<template>
  <section class="panel">
    <div class="panel-header">Run admission</div>
    <div class="panel-body">
      <p class="muted mb-5">
        Cron times are suggestions. The dispatcher admits runs under these caps so projects do
        not stampede the host.
      </p>
      <div class="inline-form">
        <div class="field">
          <label for="sched-max">Max concurrent runs</label>
          <input
            id="sched-max"
            v-model.number="scheduling.maxConcurrentRuns"
            class="input"
            type="number"
            min="1"
          />
        </div>
        <div class="field">
          <label for="sched-per-project">Max per project</label>
          <input
            id="sched-per-project"
            v-model.number="scheduling.maxConcurrentRunsPerProject"
            class="input"
            type="number"
            min="1"
          />
        </div>
        <div class="field">
          <label for="sched-stagger">Stagger (ms)</label>
          <input
            id="sched-stagger"
            v-model.number="scheduling.minStartIntervalMs"
            class="input"
            type="number"
            min="0"
            step="1000"
          />
        </div>
        <div class="field">
          <label for="sched-load">Max load / CPU (0=off)</label>
          <input
            id="sched-load"
            v-model.number="scheduling.maxLoadPerCpu"
            class="input"
            type="number"
            min="0"
            step="0.1"
          />
        </div>
      </div>
      <div class="toolbar mt-5">
        <AppButton
          variant="primary"
          size="sm"
          :icon="Save"
          :loading="busy"
          loading-label="Saving…"
          @click="saveScheduling"
        >
          Save admission policy
        </AppButton>
      </div>
    </div>
  </section>
</template>

// web/src/contexts/scheduling/components/SettingsSchedulingSection.tsx
import { useCallback, useEffect, useState } from "react";
import { AppTextfield as Textfield } from "@/ui/AppTextfield";
import { Save } from "lucide-react";

import {
  getSchedulingPolicy,
  updateSchedulingPolicy,
} from "@/contexts/scheduling/contract";
import { AppButton } from "@/ui/AppButton";
import type { SchedulingPolicy } from "@/contexts/scheduling/types";

const DEFAULT: SchedulingPolicy = {
  maxConcurrentRuns: 2,
  maxConcurrentRunsPerProject: 1,
  minStartIntervalMs: 30_000,
  maxLoadPerCpu: 1,
};

export function SettingsSchedulingSection({
  onError,
  onMessage,
}: {
  onError: (msg: string) => void;
  onMessage: (msg: string) => void;
}) {
  const [scheduling, setScheduling] = useState<SchedulingPolicy>(DEFAULT);
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    setScheduling(await getSchedulingPolicy());
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  async function save() {
    setBusy(true);
    try {
      const next = await updateSchedulingPolicy({
        maxConcurrentRuns: Number(scheduling.maxConcurrentRuns),
        maxConcurrentRunsPerProject: Number(scheduling.maxConcurrentRunsPerProject),
        minStartIntervalMs: Number(scheduling.minStartIntervalMs),
        maxLoadPerCpu: Number(scheduling.maxLoadPerCpu),
      });
      setScheduling(next);
      onMessage("Scheduling policy saved");
    } catch (err) {
      onError(err instanceof Error ? err.message : "Failed to save scheduling policy");
    } finally {
      setBusy(false);
    }
  }

  function numField(id: string, label: string, key: keyof SchedulingPolicy, step?: number) {
    return (
      <div className="field">
        <label htmlFor={id}>{label}</label>
        <Textfield
          id={id}
          type="number"
          step={step}
          value={String(scheduling[key])}
          onChange={(e) =>
            setScheduling((prev) => ({ ...prev, [key]: Number(e.currentTarget.value) || 0 }))
          }
        />
      </div>
    );
  }

  return (
    <section className="panel">
      <div className="panel-header">Run admission</div>
      <div className="panel-body">
        <p className="muted mb-5">
          Cron times are suggestions. The dispatcher admits runs under these caps so projects do
          not stampede the host.
        </p>
        <div className="inline-form">
          {numField("sched-max", "Max concurrent runs", "maxConcurrentRuns")}
          {numField("sched-per-project", "Max per project", "maxConcurrentRunsPerProject")}
          {numField("sched-stagger", "Stagger (ms)", "minStartIntervalMs", 1000)}
          {numField("sched-load", "Max load / CPU (0=off)", "maxLoadPerCpu", 0.1)}
        </div>
        <div className="toolbar mt-5">
          <AppButton
            variant="primary"
            size="sm"
            loading={busy}
            loadingLabel="Saving…"
            onClick={() => void save()}
            iconBefore={<Save size={12} />}
          >
            Save admission policy
          </AppButton>
        </div>
      </div>
    </section>
  );
}
