// web/src/ui/ConfirmDialog.tsx
import type { ReactNode } from "react";
import { Check, Trash2, X } from "lucide-react";

import { AppButton } from "@/ui/AppButton";
import { ModalDialog } from "@/ui/ModalDialog";

export type ConfirmDialogProps = {
  open: boolean;
  title: string;
  confirmLabel?: string;
  cancelLabel?: string;
  danger?: boolean;
  busy?: boolean;
  busyLabel?: string;
  onClose: () => void;
  onConfirm: () => void;
  children?: ReactNode;
};

export function ConfirmDialog({
  open,
  title,
  confirmLabel = "Confirm",
  cancelLabel = "Cancel",
  danger = false,
  busy = false,
  busyLabel = "Working…",
  onClose,
  onConfirm,
  children,
}: ConfirmDialogProps) {
  return (
    <ModalDialog
      open={open}
      title={title}
      onClose={busy ? () => {} : onClose}
      footer={
        <>
          <AppButton onClick={onClose} disabled={busy} iconBefore={<X size={14} aria-hidden="true" />}>
            {cancelLabel}
          </AppButton>
          <AppButton
            variant={danger ? "danger" : "primary"}
            loading={busy}
            loadingLabel={busyLabel}
            onClick={onConfirm}
            iconBefore={
              danger ? <Trash2 size={14} aria-hidden="true" /> : <Check size={14} aria-hidden="true" />
            }
          >
            {confirmLabel}
          </AppButton>
        </>
      }
    >
      {children}
    </ModalDialog>
  );
}

// web/src/components/ConfirmDialog.vue
<script setup lang="ts">
import { onMounted, onUnmounted, watch } from "vue";
import { Check, Trash2, X } from "lucide-vue-next";

import AppButton from "@/components/AppButton.vue";

const props = withDefaults(
  defineProps<{
    open: boolean;
    title: string;
    confirmLabel?: string;
    cancelLabel?: string;
    danger?: boolean;
    busy?: boolean;
    busyLabel?: string;
  }>(),
  {
    confirmLabel: "Confirm",
    cancelLabel: "Cancel",
    danger: false,
    busy: false,
    busyLabel: "Working…",
  },
);

const emit = defineEmits<{
  close: [];
  confirm: [];
}>();

function onKeydown(event: KeyboardEvent) {
  if (!props.open) {
    return;
  }
  if (event.key === "Escape" && !props.busy) {
    emit("close");
  }
}

watch(
  () => props.open,
  (isOpen) => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
  },
);

onMounted(() => {
  window.addEventListener("keydown", onKeydown);
});

onUnmounted(() => {
  window.removeEventListener("keydown", onKeydown);
  document.body.style.overflow = "";
});
</script>

<template>
  <div
    v-if="open"
    class="picker-backdrop"
    role="dialog"
    aria-modal="true"
    :aria-label="title"
    @click.self="!busy && emit('close')"
  >
    <div class="confirm-dialog">
      <header class="confirm-dialog-header">
        <div class="confirm-dialog-title">{{ title }}</div>
      </header>
      <div class="confirm-dialog-body">
        <slot />
      </div>
      <footer class="confirm-dialog-footer">
        <AppButton :icon="X" :disabled="busy" @click="emit('close')">
          {{ cancelLabel }}
        </AppButton>
        <AppButton
          :variant="danger ? 'danger' : 'primary'"
          :icon="danger ? Trash2 : Check"
          :loading="busy"
          :loading-label="busyLabel"
          @click="emit('confirm')"
        >
          {{ confirmLabel }}
        </AppButton>
      </footer>
    </div>
  </div>
</template>
