// web/src/ui/SortableTh.tsx
import type { SortOrder } from "@/kernel/pagination";

export type SortableThProps = {
  column: string;
  label: string;
  sort: string;
  order: SortOrder;
  defaultOrder?: SortOrder;
  onSort: (column: string, firstOrder: SortOrder) => void;
};

export function SortableTh({
  column,
  label,
  sort,
  order,
  defaultOrder,
  onSort,
}: SortableThProps) {
  const active = sort === column;
  const ariaSort: "ascending" | "descending" | "none" = active
    ? order === "asc"
      ? "ascending"
      : "descending"
    : "none";
  const indicator = active ? (order === "asc" ? "↑" : "↓") : "↕";

  return (
    <th aria-sort={ariaSort} className="sortable-th">
      <button
        type="button"
        className={`sortable-th__btn${active ? " is-active" : ""}`}
        onClick={() => onSort(column, defaultOrder ?? "asc")}
      >
        <span>{label}</span>
        <span className="sortable-th__ind" aria-hidden="true">
          {indicator}
        </span>
      </button>
    </th>
  );
}

// web/src/components/SortableTh.vue
<script setup lang="ts">
import type { SortOrder } from "@/lib/pagination";

const props = defineProps<{
  column: string;
  label: string;
  sort: string;
  order: SortOrder;
  /** Preferred order on first click when this column is inactive. */
  defaultOrder?: SortOrder;
}>();

const emit = defineEmits<{
  sort: [column: string, firstOrder: SortOrder];
}>();

const active = () => props.sort === props.column;

const ariaSort = (): "ascending" | "descending" | "none" => {
  if (!active()) {
    return "none";
  }
  return props.order === "asc" ? "ascending" : "descending";
};

const indicator = (): string => {
  if (!active()) {
    return "↕";
  }
  return props.order === "asc" ? "↑" : "↓";
};

function onClick() {
  emit("sort", props.column, props.defaultOrder ?? "asc");
}
</script>

<template>
  <th :aria-sort="ariaSort()" class="sortable-th">
    <button
      type="button"
      class="sortable-th__btn"
      :class="{ 'is-active': active() }"
      @click="onClick"
    >
      <span>{{ label }}</span>
      <span class="sortable-th__ind" aria-hidden="true">{{ indicator() }}</span>
    </button>
  </th>
</template>
