// web/src/ui/StatTile.tsx
import { useMemo, type ReactNode } from "react";
import { Link } from "react-router-dom";

import { MetricDelta } from "@/ui/MetricDelta";
import { UiIcon } from "@/ui/UiIcon";
import { formatMergeRate } from "@/kernel/impact-format";
import {
  impactCategorySpec,
  METRICS,
  metricAriaLabel,
  metricDelta,
  metricTone,
} from "@/kernel/stat-metrics";

const IMPACT_CATEGORY_PREFIX = "impact.category.";

export type StatTileProps = {
  metricKey: string;
  value: string | number | null;
  previous?: number | null;
  compareLabel?: string;
  to?: string;
  href?: string;
};

export function StatTile({ metricKey, value, previous, compareLabel, to, href }: StatTileProps) {
  const spec = useMemo(() => {
    if (metricKey.startsWith(IMPACT_CATEGORY_PREFIX)) {
      return impactCategorySpec(metricKey.slice(IMPACT_CATEGORY_PREFIX.length));
    }
    return METRICS[metricKey];
  }, [metricKey]);

  const numericValue = typeof value === "number" ? value : null;

  const displayValue = useMemo(() => {
    if (value === null || value === undefined) return "—";
    if (typeof value === "string") return value;
    if (spec?.kind === "ratio") return formatMergeRate(value);
    return String(value);
  }, [value, spec]);

  const delta = numericValue === null ? null : metricDelta(numericValue, previous);
  const tone = spec ? metricTone(spec, numericValue ?? value ?? 0) : "neutral";
  const showAttentionFlag = spec?.attention && numericValue !== null && numericValue > 0;
  const ariaLabel = spec
    ? metricAriaLabel(spec, displayValue, delta, compareLabel)
    : displayValue;

  const className = `stat-tile stat-tile--${tone}`;
  const content: ReactNode = (
    <>
      {showAttentionFlag ? <span className="stat-tile__flag" aria-hidden="true" /> : null}
      <div className="stat-tile__header">
        <span className="stat-tile__icon" aria-hidden="true">
          {spec ? <UiIcon icon={spec.icon} size={16} /> : null}
        </span>
        <span className="stat-tile__label">{spec?.label ?? metricKey}</span>
      </div>
      <span className="stat-tile__value">{displayValue}</span>
      {spec && delta !== null ? (
        <MetricDelta delta={delta} direction={spec.direction} title={compareLabel} />
      ) : null}
    </>
  );

  if (to) {
    return (
      <Link to={to} className={className} aria-label={ariaLabel} title={spec?.hint}>
        {content}
      </Link>
    );
  }
  if (href) {
    return (
      <a
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        className={className}
        aria-label={ariaLabel}
        title={spec?.hint}
      >
        {content}
      </a>
    );
  }
  return (
    <div className={className} aria-label={ariaLabel} title={spec?.hint}>
      {content}
    </div>
  );
}

// web/src/components/StatTile.vue
<script setup lang="ts">
import { computed } from "vue";
import { RouterLink, type RouteLocationRaw } from "vue-router";

import MetricDelta from "@/components/MetricDelta.vue";
import UiIcon from "@/components/UiIcon.vue";
import { formatMergeRate } from "@/lib/impact-format";
import {
  impactCategorySpec,
  METRICS,
  metricAriaLabel,
  metricDelta,
  metricTone,
} from "@/lib/stat-metrics";

const props = defineProps<{
  metricKey: string;
  value: string | number | null;
  previous?: number | null;
  compareLabel?: string;
  to?: RouteLocationRaw;
  href?: string;
}>();

const IMPACT_CATEGORY_PREFIX = "impact.category.";

const spec = computed(() => {
  if (props.metricKey.startsWith(IMPACT_CATEGORY_PREFIX)) {
    return impactCategorySpec(props.metricKey.slice(IMPACT_CATEGORY_PREFIX.length));
  }
  return METRICS[props.metricKey];
});

const numericValue = computed(() =>
  typeof props.value === "number" ? props.value : null,
);

const displayValue = computed(() => {
  if (props.value === null || props.value === undefined) {
    return "—";
  }
  if (typeof props.value === "string") {
    return props.value;
  }
  const s = spec.value;
  if (s?.kind === "ratio") {
    return formatMergeRate(props.value);
  }
  return String(props.value);
});

const delta = computed(() => {
  if (numericValue.value === null) {
    return null;
  }
  return metricDelta(numericValue.value, props.previous);
});

const tone = computed(() => {
  const s = spec.value;
  if (!s) {
    return "neutral";
  }
  return metricTone(s, numericValue.value ?? props.value ?? 0);
});

const showAttentionFlag = computed(() => {
  const s = spec.value;
  return s?.attention && numericValue.value !== null && numericValue.value > 0;
});

const ariaLabel = computed(() => {
  const s = spec.value;
  if (!s) {
    return displayValue.value;
  }
  return metricAriaLabel(s, displayValue.value, delta.value, props.compareLabel);
});

const rootTag = computed(() => {
  if (props.to) {
    return RouterLink;
  }
  if (props.href) {
    return "a";
  }
  return "div";
});

const rootProps = computed(() => {
  if (props.to) {
    return { to: props.to };
  }
  if (props.href) {
    return { href: props.href };
  }
  return {};
});
</script>

<template>
  <component
    :is="rootTag"
    class="stat-tile"
    :class="`stat-tile--${tone}`"
    v-bind="rootProps"
    :aria-label="ariaLabel"
    :title="spec?.hint"
  >
    <span v-if="showAttentionFlag" class="stat-tile__flag" aria-hidden="true" />
    <div class="stat-tile__header">
      <span class="stat-tile__icon" aria-hidden="true">
        <UiIcon v-if="spec" :icon="spec.icon" :size="16" />
      </span>
      <span class="stat-tile__label">{{ spec?.label ?? metricKey }}</span>
    </div>
    <span class="stat-tile__value">{{ displayValue }}</span>
    <MetricDelta
      v-if="spec && delta !== null"
      :delta="delta"
      :direction="spec.direction"
      :title="compareLabel"
    />
  </component>
</template>
